syntax = "proto3";
package yy.protocol.app;

// 重要，开启该选项才会生成service代码
option cc_generic_services = true;

message C2SLogin {
    uint64 session_id = 1;

    string username = 3;
    string password = 4;
}

message S2CLogin {
    uint64 session_id = 1;

    enum Status {
        eSuccess = 0;
        eAccountNotExist = 1;
        ePasswordError = 2;
        eUnknownError = 3;
    }
    Status result_code = 2;

    optional string username = 3;
    optional string ip = 4;
    optional uint32 port = 5;
    optional string token = 6;
}

message C2SRegister {
    uint64 session_id = 1;

    string username = 3;
    string password = 4;
}

message S2CRegister {
    uint64 session_id = 1;

    enum Status {
        eSuccess = 0;
        eAccountAlreadyExist = 2;
        eUnknownError = 3;
    }
    Status result_code = 2;
}


service AccountServiceRpc
{
    rpc Login(C2SLogin) returns(S2CLogin);
    rpc Register(C2SRegister) returns(S2CRegister);
}