// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connection.proto

#include "connection.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace yy {
namespace protocol {
namespace core {
PROTOBUF_CONSTEXPR XorBody::XorBody(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.xor_code_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct XorBodyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR XorBodyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~XorBodyDefaultTypeInternal() {}
  union {
    XorBody _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 XorBodyDefaultTypeInternal _XorBody_default_instance_;
PROTOBUF_CONSTEXPR HeartBody::HeartBody(
    ::_pbi::ConstantInitialized) {}
struct HeartBodyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR HeartBodyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~HeartBodyDefaultTypeInternal() {}
  union {
    HeartBody _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 HeartBodyDefaultTypeInternal _HeartBody_default_instance_;
PROTOBUF_CONSTEXPR SecurityBody::SecurityBody(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.app_md5_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.app_id_)*/0u
  , /*decltype(_impl_.app_version_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SecurityBodyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SecurityBodyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SecurityBodyDefaultTypeInternal() {}
  union {
    SecurityBody _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SecurityBodyDefaultTypeInternal _SecurityBody_default_instance_;
PROTOBUF_CONSTEXPR ResultBody::ResultBody(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.result_code_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ResultBodyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResultBodyDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResultBodyDefaultTypeInternal() {}
  union {
    ResultBody _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResultBodyDefaultTypeInternal _ResultBody_default_instance_;
}  // namespace core
}  // namespace protocol
}  // namespace yy
static ::_pb::Metadata file_level_metadata_connection_2eproto[4];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_connection_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_connection_2eproto = nullptr;

const uint32_t TableStruct_connection_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yy::protocol::core::XorBody, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yy::protocol::core::XorBody, _impl_.xor_code_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yy::protocol::core::HeartBody, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yy::protocol::core::SecurityBody, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yy::protocol::core::SecurityBody, _impl_.app_id_),
  PROTOBUF_FIELD_OFFSET(::yy::protocol::core::SecurityBody, _impl_.app_version_),
  PROTOBUF_FIELD_OFFSET(::yy::protocol::core::SecurityBody, _impl_.app_md5_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yy::protocol::core::ResultBody, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yy::protocol::core::ResultBody, _impl_.result_code_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::yy::protocol::core::XorBody)},
  { 7, -1, -1, sizeof(::yy::protocol::core::HeartBody)},
  { 13, -1, -1, sizeof(::yy::protocol::core::SecurityBody)},
  { 22, -1, -1, sizeof(::yy::protocol::core::ResultBody)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::yy::protocol::core::_XorBody_default_instance_._instance,
  &::yy::protocol::core::_HeartBody_default_instance_._instance,
  &::yy::protocol::core::_SecurityBody_default_instance_._instance,
  &::yy::protocol::core::_ResultBody_default_instance_._instance,
};

const char descriptor_table_protodef_connection_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020connection.proto\022\020yy.protocol.core\"\033\n\007"
  "XorBody\022\020\n\010xor_code\030\001 \001(\r\"\013\n\tHeartBody\"D"
  "\n\014SecurityBody\022\016\n\006app_id\030\001 \001(\r\022\023\n\013app_ve"
  "rsion\030\002 \001(\r\022\017\n\007app_md5\030\003 \001(\t\"\?\n\nResultBo"
  "dy\0221\n\013result_code\030\001 \001(\0162\034.yy.protocol.co"
  "re.ResultCode*A\n\nResultCode\022\014\n\010eSuccess\020"
  "\000\022\025\n\021eAppVersionFailed\020\001\022\016\n\neMd5Failed\020\002"
  "b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_connection_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_connection_2eproto = {
    false, false, 288, descriptor_table_protodef_connection_2eproto,
    "connection.proto",
    &descriptor_table_connection_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_connection_2eproto::offsets,
    file_level_metadata_connection_2eproto, file_level_enum_descriptors_connection_2eproto,
    file_level_service_descriptors_connection_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_connection_2eproto_getter() {
  return &descriptor_table_connection_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_connection_2eproto(&descriptor_table_connection_2eproto);
namespace yy {
namespace protocol {
namespace core {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ResultCode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_connection_2eproto);
  return file_level_enum_descriptors_connection_2eproto[0];
}
bool ResultCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

class XorBody::_Internal {
 public:
};

XorBody::XorBody(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:yy.protocol.core.XorBody)
}
XorBody::XorBody(const XorBody& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  XorBody* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.xor_code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.xor_code_ = from._impl_.xor_code_;
  // @@protoc_insertion_point(copy_constructor:yy.protocol.core.XorBody)
}

inline void XorBody::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.xor_code_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

XorBody::~XorBody() {
  // @@protoc_insertion_point(destructor:yy.protocol.core.XorBody)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void XorBody::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void XorBody::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void XorBody::Clear() {
// @@protoc_insertion_point(message_clear_start:yy.protocol.core.XorBody)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.xor_code_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* XorBody::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 xor_code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.xor_code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* XorBody::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yy.protocol.core.XorBody)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 xor_code = 1;
  if (this->_internal_xor_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_xor_code(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yy.protocol.core.XorBody)
  return target;
}

size_t XorBody::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yy.protocol.core.XorBody)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 xor_code = 1;
  if (this->_internal_xor_code() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_xor_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData XorBody::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    XorBody::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*XorBody::GetClassData() const { return &_class_data_; }


void XorBody::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<XorBody*>(&to_msg);
  auto& from = static_cast<const XorBody&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:yy.protocol.core.XorBody)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_xor_code() != 0) {
    _this->_internal_set_xor_code(from._internal_xor_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void XorBody::CopyFrom(const XorBody& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yy.protocol.core.XorBody)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool XorBody::IsInitialized() const {
  return true;
}

void XorBody::InternalSwap(XorBody* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.xor_code_, other->_impl_.xor_code_);
}

::PROTOBUF_NAMESPACE_ID::Metadata XorBody::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_connection_2eproto_getter, &descriptor_table_connection_2eproto_once,
      file_level_metadata_connection_2eproto[0]);
}

// ===================================================================

class HeartBody::_Internal {
 public:
};

HeartBody::HeartBody(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:yy.protocol.core.HeartBody)
}
HeartBody::HeartBody(const HeartBody& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  HeartBody* const _this = this; (void)_this;
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:yy.protocol.core.HeartBody)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData HeartBody::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*HeartBody::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata HeartBody::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_connection_2eproto_getter, &descriptor_table_connection_2eproto_once,
      file_level_metadata_connection_2eproto[1]);
}

// ===================================================================

class SecurityBody::_Internal {
 public:
};

SecurityBody::SecurityBody(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:yy.protocol.core.SecurityBody)
}
SecurityBody::SecurityBody(const SecurityBody& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SecurityBody* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.app_md5_){}
    , decltype(_impl_.app_id_){}
    , decltype(_impl_.app_version_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.app_md5_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.app_md5_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_app_md5().empty()) {
    _this->_impl_.app_md5_.Set(from._internal_app_md5(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.app_id_, &from._impl_.app_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.app_version_) -
    reinterpret_cast<char*>(&_impl_.app_id_)) + sizeof(_impl_.app_version_));
  // @@protoc_insertion_point(copy_constructor:yy.protocol.core.SecurityBody)
}

inline void SecurityBody::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.app_md5_){}
    , decltype(_impl_.app_id_){0u}
    , decltype(_impl_.app_version_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.app_md5_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.app_md5_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SecurityBody::~SecurityBody() {
  // @@protoc_insertion_point(destructor:yy.protocol.core.SecurityBody)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SecurityBody::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.app_md5_.Destroy();
}

void SecurityBody::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SecurityBody::Clear() {
// @@protoc_insertion_point(message_clear_start:yy.protocol.core.SecurityBody)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.app_md5_.ClearToEmpty();
  ::memset(&_impl_.app_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.app_version_) -
      reinterpret_cast<char*>(&_impl_.app_id_)) + sizeof(_impl_.app_version_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SecurityBody::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 app_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.app_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 app_version = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.app_version_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string app_md5 = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_app_md5();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "yy.protocol.core.SecurityBody.app_md5"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SecurityBody::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yy.protocol.core.SecurityBody)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 app_id = 1;
  if (this->_internal_app_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_app_id(), target);
  }

  // uint32 app_version = 2;
  if (this->_internal_app_version() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_app_version(), target);
  }

  // string app_md5 = 3;
  if (!this->_internal_app_md5().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_app_md5().data(), static_cast<int>(this->_internal_app_md5().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yy.protocol.core.SecurityBody.app_md5");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_app_md5(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yy.protocol.core.SecurityBody)
  return target;
}

size_t SecurityBody::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yy.protocol.core.SecurityBody)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string app_md5 = 3;
  if (!this->_internal_app_md5().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_app_md5());
  }

  // uint32 app_id = 1;
  if (this->_internal_app_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_app_id());
  }

  // uint32 app_version = 2;
  if (this->_internal_app_version() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_app_version());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SecurityBody::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SecurityBody::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SecurityBody::GetClassData() const { return &_class_data_; }


void SecurityBody::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SecurityBody*>(&to_msg);
  auto& from = static_cast<const SecurityBody&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:yy.protocol.core.SecurityBody)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_app_md5().empty()) {
    _this->_internal_set_app_md5(from._internal_app_md5());
  }
  if (from._internal_app_id() != 0) {
    _this->_internal_set_app_id(from._internal_app_id());
  }
  if (from._internal_app_version() != 0) {
    _this->_internal_set_app_version(from._internal_app_version());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SecurityBody::CopyFrom(const SecurityBody& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yy.protocol.core.SecurityBody)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SecurityBody::IsInitialized() const {
  return true;
}

void SecurityBody::InternalSwap(SecurityBody* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.app_md5_, lhs_arena,
      &other->_impl_.app_md5_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SecurityBody, _impl_.app_version_)
      + sizeof(SecurityBody::_impl_.app_version_)
      - PROTOBUF_FIELD_OFFSET(SecurityBody, _impl_.app_id_)>(
          reinterpret_cast<char*>(&_impl_.app_id_),
          reinterpret_cast<char*>(&other->_impl_.app_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SecurityBody::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_connection_2eproto_getter, &descriptor_table_connection_2eproto_once,
      file_level_metadata_connection_2eproto[2]);
}

// ===================================================================

class ResultBody::_Internal {
 public:
};

ResultBody::ResultBody(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:yy.protocol.core.ResultBody)
}
ResultBody::ResultBody(const ResultBody& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ResultBody* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.result_code_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.result_code_ = from._impl_.result_code_;
  // @@protoc_insertion_point(copy_constructor:yy.protocol.core.ResultBody)
}

inline void ResultBody::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.result_code_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ResultBody::~ResultBody() {
  // @@protoc_insertion_point(destructor:yy.protocol.core.ResultBody)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ResultBody::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void ResultBody::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ResultBody::Clear() {
// @@protoc_insertion_point(message_clear_start:yy.protocol.core.ResultBody)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.result_code_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ResultBody::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .yy.protocol.core.ResultCode result_code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_result_code(static_cast<::yy::protocol::core::ResultCode>(val));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ResultBody::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yy.protocol.core.ResultBody)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .yy.protocol.core.ResultCode result_code = 1;
  if (this->_internal_result_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
      1, this->_internal_result_code(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yy.protocol.core.ResultBody)
  return target;
}

size_t ResultBody::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yy.protocol.core.ResultBody)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .yy.protocol.core.ResultCode result_code = 1;
  if (this->_internal_result_code() != 0) {
    total_size += 1 +
      ::_pbi::WireFormatLite::EnumSize(this->_internal_result_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ResultBody::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ResultBody::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ResultBody::GetClassData() const { return &_class_data_; }


void ResultBody::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ResultBody*>(&to_msg);
  auto& from = static_cast<const ResultBody&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:yy.protocol.core.ResultBody)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_result_code() != 0) {
    _this->_internal_set_result_code(from._internal_result_code());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ResultBody::CopyFrom(const ResultBody& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yy.protocol.core.ResultBody)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResultBody::IsInitialized() const {
  return true;
}

void ResultBody::InternalSwap(ResultBody* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.result_code_, other->_impl_.result_code_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ResultBody::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_connection_2eproto_getter, &descriptor_table_connection_2eproto_once,
      file_level_metadata_connection_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace core
}  // namespace protocol
}  // namespace yy
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::yy::protocol::core::XorBody*
Arena::CreateMaybeMessage< ::yy::protocol::core::XorBody >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yy::protocol::core::XorBody >(arena);
}
template<> PROTOBUF_NOINLINE ::yy::protocol::core::HeartBody*
Arena::CreateMaybeMessage< ::yy::protocol::core::HeartBody >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yy::protocol::core::HeartBody >(arena);
}
template<> PROTOBUF_NOINLINE ::yy::protocol::core::SecurityBody*
Arena::CreateMaybeMessage< ::yy::protocol::core::SecurityBody >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yy::protocol::core::SecurityBody >(arena);
}
template<> PROTOBUF_NOINLINE ::yy::protocol::core::ResultBody*
Arena::CreateMaybeMessage< ::yy::protocol::core::ResultBody >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yy::protocol::core::ResultBody >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
