// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: connection.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_connection_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_connection_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_bases.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_connection_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_connection_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_connection_2eproto;
namespace yy {
namespace protocol {
namespace core {
class C2SSecurityBody;
struct C2SSecurityBodyDefaultTypeInternal;
extern C2SSecurityBodyDefaultTypeInternal _C2SSecurityBody_default_instance_;
class C2SUdpPortRegister;
struct C2SUdpPortRegisterDefaultTypeInternal;
extern C2SUdpPortRegisterDefaultTypeInternal _C2SUdpPortRegister_default_instance_;
class HeartBody;
struct HeartBodyDefaultTypeInternal;
extern HeartBodyDefaultTypeInternal _HeartBody_default_instance_;
class S2CSecurityBody;
struct S2CSecurityBodyDefaultTypeInternal;
extern S2CSecurityBodyDefaultTypeInternal _S2CSecurityBody_default_instance_;
class S2CUdpPortRegister;
struct S2CUdpPortRegisterDefaultTypeInternal;
extern S2CUdpPortRegisterDefaultTypeInternal _S2CUdpPortRegister_default_instance_;
class S2CXorBody;
struct S2CXorBodyDefaultTypeInternal;
extern S2CXorBodyDefaultTypeInternal _S2CXorBody_default_instance_;
}  // namespace core
}  // namespace protocol
}  // namespace yy
PROTOBUF_NAMESPACE_OPEN
template<> ::yy::protocol::core::C2SSecurityBody* Arena::CreateMaybeMessage<::yy::protocol::core::C2SSecurityBody>(Arena*);
template<> ::yy::protocol::core::C2SUdpPortRegister* Arena::CreateMaybeMessage<::yy::protocol::core::C2SUdpPortRegister>(Arena*);
template<> ::yy::protocol::core::HeartBody* Arena::CreateMaybeMessage<::yy::protocol::core::HeartBody>(Arena*);
template<> ::yy::protocol::core::S2CSecurityBody* Arena::CreateMaybeMessage<::yy::protocol::core::S2CSecurityBody>(Arena*);
template<> ::yy::protocol::core::S2CUdpPortRegister* Arena::CreateMaybeMessage<::yy::protocol::core::S2CUdpPortRegister>(Arena*);
template<> ::yy::protocol::core::S2CXorBody* Arena::CreateMaybeMessage<::yy::protocol::core::S2CXorBody>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace yy {
namespace protocol {
namespace core {

enum S2CSecurityBody_ResultCode : int {
  S2CSecurityBody_ResultCode_eSuccess = 0,
  S2CSecurityBody_ResultCode_eAppVersionFailed = 1,
  S2CSecurityBody_ResultCode_eMd5Failed = 2,
  S2CSecurityBody_ResultCode_S2CSecurityBody_ResultCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  S2CSecurityBody_ResultCode_S2CSecurityBody_ResultCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool S2CSecurityBody_ResultCode_IsValid(int value);
constexpr S2CSecurityBody_ResultCode S2CSecurityBody_ResultCode_ResultCode_MIN = S2CSecurityBody_ResultCode_eSuccess;
constexpr S2CSecurityBody_ResultCode S2CSecurityBody_ResultCode_ResultCode_MAX = S2CSecurityBody_ResultCode_eMd5Failed;
constexpr int S2CSecurityBody_ResultCode_ResultCode_ARRAYSIZE = S2CSecurityBody_ResultCode_ResultCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* S2CSecurityBody_ResultCode_descriptor();
template<typename T>
inline const std::string& S2CSecurityBody_ResultCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, S2CSecurityBody_ResultCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function S2CSecurityBody_ResultCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    S2CSecurityBody_ResultCode_descriptor(), enum_t_value);
}
inline bool S2CSecurityBody_ResultCode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, S2CSecurityBody_ResultCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<S2CSecurityBody_ResultCode>(
    S2CSecurityBody_ResultCode_descriptor(), name, value);
}
enum S2CUdpPortRegister_Status : int {
  S2CUdpPortRegister_Status_eSuccess = 0,
  S2CUdpPortRegister_Status_eInvalidPort = 1,
  S2CUdpPortRegister_Status_eDuplicatePort = 2,
  S2CUdpPortRegister_Status_S2CUdpPortRegister_Status_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  S2CUdpPortRegister_Status_S2CUdpPortRegister_Status_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool S2CUdpPortRegister_Status_IsValid(int value);
constexpr S2CUdpPortRegister_Status S2CUdpPortRegister_Status_Status_MIN = S2CUdpPortRegister_Status_eSuccess;
constexpr S2CUdpPortRegister_Status S2CUdpPortRegister_Status_Status_MAX = S2CUdpPortRegister_Status_eDuplicatePort;
constexpr int S2CUdpPortRegister_Status_Status_ARRAYSIZE = S2CUdpPortRegister_Status_Status_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* S2CUdpPortRegister_Status_descriptor();
template<typename T>
inline const std::string& S2CUdpPortRegister_Status_Name(T enum_t_value) {
  static_assert(::std::is_same<T, S2CUdpPortRegister_Status>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function S2CUdpPortRegister_Status_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    S2CUdpPortRegister_Status_descriptor(), enum_t_value);
}
inline bool S2CUdpPortRegister_Status_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, S2CUdpPortRegister_Status* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<S2CUdpPortRegister_Status>(
    S2CUdpPortRegister_Status_descriptor(), name, value);
}
// ===================================================================

class S2CXorBody final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yy.protocol.core.S2CXorBody) */ {
 public:
  inline S2CXorBody() : S2CXorBody(nullptr) {}
  ~S2CXorBody() override;
  explicit PROTOBUF_CONSTEXPR S2CXorBody(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S2CXorBody(const S2CXorBody& from);
  S2CXorBody(S2CXorBody&& from) noexcept
    : S2CXorBody() {
    *this = ::std::move(from);
  }

  inline S2CXorBody& operator=(const S2CXorBody& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2CXorBody& operator=(S2CXorBody&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S2CXorBody& default_instance() {
    return *internal_default_instance();
  }
  static inline const S2CXorBody* internal_default_instance() {
    return reinterpret_cast<const S2CXorBody*>(
               &_S2CXorBody_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(S2CXorBody& a, S2CXorBody& b) {
    a.Swap(&b);
  }
  inline void Swap(S2CXorBody* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S2CXorBody* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S2CXorBody* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S2CXorBody>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S2CXorBody& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S2CXorBody& from) {
    S2CXorBody::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S2CXorBody* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yy.protocol.core.S2CXorBody";
  }
  protected:
  explicit S2CXorBody(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXorCodeFieldNumber = 1,
  };
  // uint32 xor_code = 1;
  void clear_xor_code();
  uint32_t xor_code() const;
  void set_xor_code(uint32_t value);
  private:
  uint32_t _internal_xor_code() const;
  void _internal_set_xor_code(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:yy.protocol.core.S2CXorBody)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t xor_code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_connection_2eproto;
};
// -------------------------------------------------------------------

class HeartBody final :
    public ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase /* @@protoc_insertion_point(class_definition:yy.protocol.core.HeartBody) */ {
 public:
  inline HeartBody() : HeartBody(nullptr) {}
  explicit PROTOBUF_CONSTEXPR HeartBody(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HeartBody(const HeartBody& from);
  HeartBody(HeartBody&& from) noexcept
    : HeartBody() {
    *this = ::std::move(from);
  }

  inline HeartBody& operator=(const HeartBody& from) {
    CopyFrom(from);
    return *this;
  }
  inline HeartBody& operator=(HeartBody&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HeartBody& default_instance() {
    return *internal_default_instance();
  }
  static inline const HeartBody* internal_default_instance() {
    return reinterpret_cast<const HeartBody*>(
               &_HeartBody_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(HeartBody& a, HeartBody& b) {
    a.Swap(&b);
  }
  inline void Swap(HeartBody* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HeartBody* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HeartBody* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HeartBody>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const HeartBody& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const HeartBody& from) {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }
  public:

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yy.protocol.core.HeartBody";
  }
  protected:
  explicit HeartBody(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:yy.protocol.core.HeartBody)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
  };
  friend struct ::TableStruct_connection_2eproto;
};
// -------------------------------------------------------------------

class C2SSecurityBody final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yy.protocol.core.C2SSecurityBody) */ {
 public:
  inline C2SSecurityBody() : C2SSecurityBody(nullptr) {}
  ~C2SSecurityBody() override;
  explicit PROTOBUF_CONSTEXPR C2SSecurityBody(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C2SSecurityBody(const C2SSecurityBody& from);
  C2SSecurityBody(C2SSecurityBody&& from) noexcept
    : C2SSecurityBody() {
    *this = ::std::move(from);
  }

  inline C2SSecurityBody& operator=(const C2SSecurityBody& from) {
    CopyFrom(from);
    return *this;
  }
  inline C2SSecurityBody& operator=(C2SSecurityBody&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C2SSecurityBody& default_instance() {
    return *internal_default_instance();
  }
  static inline const C2SSecurityBody* internal_default_instance() {
    return reinterpret_cast<const C2SSecurityBody*>(
               &_C2SSecurityBody_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(C2SSecurityBody& a, C2SSecurityBody& b) {
    a.Swap(&b);
  }
  inline void Swap(C2SSecurityBody* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C2SSecurityBody* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C2SSecurityBody* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C2SSecurityBody>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C2SSecurityBody& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C2SSecurityBody& from) {
    C2SSecurityBody::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C2SSecurityBody* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yy.protocol.core.C2SSecurityBody";
  }
  protected:
  explicit C2SSecurityBody(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAppMd5FieldNumber = 3,
    kAppIdFieldNumber = 1,
    kAppVersionFieldNumber = 2,
  };
  // string app_md5 = 3;
  void clear_app_md5();
  const std::string& app_md5() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_app_md5(ArgT0&& arg0, ArgT... args);
  std::string* mutable_app_md5();
  PROTOBUF_NODISCARD std::string* release_app_md5();
  void set_allocated_app_md5(std::string* app_md5);
  private:
  const std::string& _internal_app_md5() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_app_md5(const std::string& value);
  std::string* _internal_mutable_app_md5();
  public:

  // uint32 app_id = 1;
  void clear_app_id();
  uint32_t app_id() const;
  void set_app_id(uint32_t value);
  private:
  uint32_t _internal_app_id() const;
  void _internal_set_app_id(uint32_t value);
  public:

  // uint32 app_version = 2;
  void clear_app_version();
  uint32_t app_version() const;
  void set_app_version(uint32_t value);
  private:
  uint32_t _internal_app_version() const;
  void _internal_set_app_version(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:yy.protocol.core.C2SSecurityBody)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr app_md5_;
    uint32_t app_id_;
    uint32_t app_version_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_connection_2eproto;
};
// -------------------------------------------------------------------

class S2CSecurityBody final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yy.protocol.core.S2CSecurityBody) */ {
 public:
  inline S2CSecurityBody() : S2CSecurityBody(nullptr) {}
  ~S2CSecurityBody() override;
  explicit PROTOBUF_CONSTEXPR S2CSecurityBody(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S2CSecurityBody(const S2CSecurityBody& from);
  S2CSecurityBody(S2CSecurityBody&& from) noexcept
    : S2CSecurityBody() {
    *this = ::std::move(from);
  }

  inline S2CSecurityBody& operator=(const S2CSecurityBody& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2CSecurityBody& operator=(S2CSecurityBody&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S2CSecurityBody& default_instance() {
    return *internal_default_instance();
  }
  static inline const S2CSecurityBody* internal_default_instance() {
    return reinterpret_cast<const S2CSecurityBody*>(
               &_S2CSecurityBody_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(S2CSecurityBody& a, S2CSecurityBody& b) {
    a.Swap(&b);
  }
  inline void Swap(S2CSecurityBody* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S2CSecurityBody* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S2CSecurityBody* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S2CSecurityBody>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S2CSecurityBody& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S2CSecurityBody& from) {
    S2CSecurityBody::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S2CSecurityBody* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yy.protocol.core.S2CSecurityBody";
  }
  protected:
  explicit S2CSecurityBody(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef S2CSecurityBody_ResultCode ResultCode;
  static constexpr ResultCode eSuccess =
    S2CSecurityBody_ResultCode_eSuccess;
  static constexpr ResultCode eAppVersionFailed =
    S2CSecurityBody_ResultCode_eAppVersionFailed;
  static constexpr ResultCode eMd5Failed =
    S2CSecurityBody_ResultCode_eMd5Failed;
  static inline bool ResultCode_IsValid(int value) {
    return S2CSecurityBody_ResultCode_IsValid(value);
  }
  static constexpr ResultCode ResultCode_MIN =
    S2CSecurityBody_ResultCode_ResultCode_MIN;
  static constexpr ResultCode ResultCode_MAX =
    S2CSecurityBody_ResultCode_ResultCode_MAX;
  static constexpr int ResultCode_ARRAYSIZE =
    S2CSecurityBody_ResultCode_ResultCode_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  ResultCode_descriptor() {
    return S2CSecurityBody_ResultCode_descriptor();
  }
  template<typename T>
  static inline const std::string& ResultCode_Name(T enum_t_value) {
    static_assert(::std::is_same<T, ResultCode>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function ResultCode_Name.");
    return S2CSecurityBody_ResultCode_Name(enum_t_value);
  }
  static inline bool ResultCode_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      ResultCode* value) {
    return S2CSecurityBody_ResultCode_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kResultCodeFieldNumber = 1,
    kServerUdpPortFieldNumber = 2,
    kSessionIdFieldNumber = 3,
  };
  // .yy.protocol.core.S2CSecurityBody.ResultCode result_code = 1;
  void clear_result_code();
  ::yy::protocol::core::S2CSecurityBody_ResultCode result_code() const;
  void set_result_code(::yy::protocol::core::S2CSecurityBody_ResultCode value);
  private:
  ::yy::protocol::core::S2CSecurityBody_ResultCode _internal_result_code() const;
  void _internal_set_result_code(::yy::protocol::core::S2CSecurityBody_ResultCode value);
  public:

  // optional uint32 server_udp_port = 2;
  bool has_server_udp_port() const;
  private:
  bool _internal_has_server_udp_port() const;
  public:
  void clear_server_udp_port();
  uint32_t server_udp_port() const;
  void set_server_udp_port(uint32_t value);
  private:
  uint32_t _internal_server_udp_port() const;
  void _internal_set_server_udp_port(uint32_t value);
  public:

  // optional uint64 session_id = 3;
  bool has_session_id() const;
  private:
  bool _internal_has_session_id() const;
  public:
  void clear_session_id();
  uint64_t session_id() const;
  void set_session_id(uint64_t value);
  private:
  uint64_t _internal_session_id() const;
  void _internal_set_session_id(uint64_t value);
  public:

  // @@protoc_insertion_point(class_scope:yy.protocol.core.S2CSecurityBody)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    int result_code_;
    uint32_t server_udp_port_;
    uint64_t session_id_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_connection_2eproto;
};
// -------------------------------------------------------------------

class C2SUdpPortRegister final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yy.protocol.core.C2SUdpPortRegister) */ {
 public:
  inline C2SUdpPortRegister() : C2SUdpPortRegister(nullptr) {}
  ~C2SUdpPortRegister() override;
  explicit PROTOBUF_CONSTEXPR C2SUdpPortRegister(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C2SUdpPortRegister(const C2SUdpPortRegister& from);
  C2SUdpPortRegister(C2SUdpPortRegister&& from) noexcept
    : C2SUdpPortRegister() {
    *this = ::std::move(from);
  }

  inline C2SUdpPortRegister& operator=(const C2SUdpPortRegister& from) {
    CopyFrom(from);
    return *this;
  }
  inline C2SUdpPortRegister& operator=(C2SUdpPortRegister&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C2SUdpPortRegister& default_instance() {
    return *internal_default_instance();
  }
  static inline const C2SUdpPortRegister* internal_default_instance() {
    return reinterpret_cast<const C2SUdpPortRegister*>(
               &_C2SUdpPortRegister_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(C2SUdpPortRegister& a, C2SUdpPortRegister& b) {
    a.Swap(&b);
  }
  inline void Swap(C2SUdpPortRegister* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C2SUdpPortRegister* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C2SUdpPortRegister* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C2SUdpPortRegister>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C2SUdpPortRegister& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C2SUdpPortRegister& from) {
    C2SUdpPortRegister::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C2SUdpPortRegister* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yy.protocol.core.C2SUdpPortRegister";
  }
  protected:
  explicit C2SUdpPortRegister(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClientUdpIpFieldNumber = 2,
    kSessionIdFieldNumber = 1,
    kClientUdpPortFieldNumber = 3,
  };
  // string client_udp_ip = 2;
  void clear_client_udp_ip();
  const std::string& client_udp_ip() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_client_udp_ip(ArgT0&& arg0, ArgT... args);
  std::string* mutable_client_udp_ip();
  PROTOBUF_NODISCARD std::string* release_client_udp_ip();
  void set_allocated_client_udp_ip(std::string* client_udp_ip);
  private:
  const std::string& _internal_client_udp_ip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_client_udp_ip(const std::string& value);
  std::string* _internal_mutable_client_udp_ip();
  public:

  // uint64 session_id = 1;
  void clear_session_id();
  uint64_t session_id() const;
  void set_session_id(uint64_t value);
  private:
  uint64_t _internal_session_id() const;
  void _internal_set_session_id(uint64_t value);
  public:

  // uint32 client_udp_port = 3;
  void clear_client_udp_port();
  uint32_t client_udp_port() const;
  void set_client_udp_port(uint32_t value);
  private:
  uint32_t _internal_client_udp_port() const;
  void _internal_set_client_udp_port(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:yy.protocol.core.C2SUdpPortRegister)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr client_udp_ip_;
    uint64_t session_id_;
    uint32_t client_udp_port_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_connection_2eproto;
};
// -------------------------------------------------------------------

class S2CUdpPortRegister final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yy.protocol.core.S2CUdpPortRegister) */ {
 public:
  inline S2CUdpPortRegister() : S2CUdpPortRegister(nullptr) {}
  ~S2CUdpPortRegister() override;
  explicit PROTOBUF_CONSTEXPR S2CUdpPortRegister(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S2CUdpPortRegister(const S2CUdpPortRegister& from);
  S2CUdpPortRegister(S2CUdpPortRegister&& from) noexcept
    : S2CUdpPortRegister() {
    *this = ::std::move(from);
  }

  inline S2CUdpPortRegister& operator=(const S2CUdpPortRegister& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2CUdpPortRegister& operator=(S2CUdpPortRegister&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S2CUdpPortRegister& default_instance() {
    return *internal_default_instance();
  }
  static inline const S2CUdpPortRegister* internal_default_instance() {
    return reinterpret_cast<const S2CUdpPortRegister*>(
               &_S2CUdpPortRegister_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(S2CUdpPortRegister& a, S2CUdpPortRegister& b) {
    a.Swap(&b);
  }
  inline void Swap(S2CUdpPortRegister* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S2CUdpPortRegister* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S2CUdpPortRegister* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S2CUdpPortRegister>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S2CUdpPortRegister& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S2CUdpPortRegister& from) {
    S2CUdpPortRegister::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S2CUdpPortRegister* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "yy.protocol.core.S2CUdpPortRegister";
  }
  protected:
  explicit S2CUdpPortRegister(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef S2CUdpPortRegister_Status Status;
  static constexpr Status eSuccess =
    S2CUdpPortRegister_Status_eSuccess;
  static constexpr Status eInvalidPort =
    S2CUdpPortRegister_Status_eInvalidPort;
  static constexpr Status eDuplicatePort =
    S2CUdpPortRegister_Status_eDuplicatePort;
  static inline bool Status_IsValid(int value) {
    return S2CUdpPortRegister_Status_IsValid(value);
  }
  static constexpr Status Status_MIN =
    S2CUdpPortRegister_Status_Status_MIN;
  static constexpr Status Status_MAX =
    S2CUdpPortRegister_Status_Status_MAX;
  static constexpr int Status_ARRAYSIZE =
    S2CUdpPortRegister_Status_Status_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Status_descriptor() {
    return S2CUdpPortRegister_Status_descriptor();
  }
  template<typename T>
  static inline const std::string& Status_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Status>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Status_Name.");
    return S2CUdpPortRegister_Status_Name(enum_t_value);
  }
  static inline bool Status_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Status* value) {
    return S2CUdpPortRegister_Status_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kStatusFieldNumber = 1,
  };
  // .yy.protocol.core.S2CUdpPortRegister.Status status = 1;
  void clear_status();
  ::yy::protocol::core::S2CUdpPortRegister_Status status() const;
  void set_status(::yy::protocol::core::S2CUdpPortRegister_Status value);
  private:
  ::yy::protocol::core::S2CUdpPortRegister_Status _internal_status() const;
  void _internal_set_status(::yy::protocol::core::S2CUdpPortRegister_Status value);
  public:

  // @@protoc_insertion_point(class_scope:yy.protocol.core.S2CUdpPortRegister)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int status_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_connection_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// S2CXorBody

// uint32 xor_code = 1;
inline void S2CXorBody::clear_xor_code() {
  _impl_.xor_code_ = 0u;
}
inline uint32_t S2CXorBody::_internal_xor_code() const {
  return _impl_.xor_code_;
}
inline uint32_t S2CXorBody::xor_code() const {
  // @@protoc_insertion_point(field_get:yy.protocol.core.S2CXorBody.xor_code)
  return _internal_xor_code();
}
inline void S2CXorBody::_internal_set_xor_code(uint32_t value) {
  
  _impl_.xor_code_ = value;
}
inline void S2CXorBody::set_xor_code(uint32_t value) {
  _internal_set_xor_code(value);
  // @@protoc_insertion_point(field_set:yy.protocol.core.S2CXorBody.xor_code)
}

// -------------------------------------------------------------------

// HeartBody

// -------------------------------------------------------------------

// C2SSecurityBody

// uint32 app_id = 1;
inline void C2SSecurityBody::clear_app_id() {
  _impl_.app_id_ = 0u;
}
inline uint32_t C2SSecurityBody::_internal_app_id() const {
  return _impl_.app_id_;
}
inline uint32_t C2SSecurityBody::app_id() const {
  // @@protoc_insertion_point(field_get:yy.protocol.core.C2SSecurityBody.app_id)
  return _internal_app_id();
}
inline void C2SSecurityBody::_internal_set_app_id(uint32_t value) {
  
  _impl_.app_id_ = value;
}
inline void C2SSecurityBody::set_app_id(uint32_t value) {
  _internal_set_app_id(value);
  // @@protoc_insertion_point(field_set:yy.protocol.core.C2SSecurityBody.app_id)
}

// uint32 app_version = 2;
inline void C2SSecurityBody::clear_app_version() {
  _impl_.app_version_ = 0u;
}
inline uint32_t C2SSecurityBody::_internal_app_version() const {
  return _impl_.app_version_;
}
inline uint32_t C2SSecurityBody::app_version() const {
  // @@protoc_insertion_point(field_get:yy.protocol.core.C2SSecurityBody.app_version)
  return _internal_app_version();
}
inline void C2SSecurityBody::_internal_set_app_version(uint32_t value) {
  
  _impl_.app_version_ = value;
}
inline void C2SSecurityBody::set_app_version(uint32_t value) {
  _internal_set_app_version(value);
  // @@protoc_insertion_point(field_set:yy.protocol.core.C2SSecurityBody.app_version)
}

// string app_md5 = 3;
inline void C2SSecurityBody::clear_app_md5() {
  _impl_.app_md5_.ClearToEmpty();
}
inline const std::string& C2SSecurityBody::app_md5() const {
  // @@protoc_insertion_point(field_get:yy.protocol.core.C2SSecurityBody.app_md5)
  return _internal_app_md5();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void C2SSecurityBody::set_app_md5(ArgT0&& arg0, ArgT... args) {
 
 _impl_.app_md5_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:yy.protocol.core.C2SSecurityBody.app_md5)
}
inline std::string* C2SSecurityBody::mutable_app_md5() {
  std::string* _s = _internal_mutable_app_md5();
  // @@protoc_insertion_point(field_mutable:yy.protocol.core.C2SSecurityBody.app_md5)
  return _s;
}
inline const std::string& C2SSecurityBody::_internal_app_md5() const {
  return _impl_.app_md5_.Get();
}
inline void C2SSecurityBody::_internal_set_app_md5(const std::string& value) {
  
  _impl_.app_md5_.Set(value, GetArenaForAllocation());
}
inline std::string* C2SSecurityBody::_internal_mutable_app_md5() {
  
  return _impl_.app_md5_.Mutable(GetArenaForAllocation());
}
inline std::string* C2SSecurityBody::release_app_md5() {
  // @@protoc_insertion_point(field_release:yy.protocol.core.C2SSecurityBody.app_md5)
  return _impl_.app_md5_.Release();
}
inline void C2SSecurityBody::set_allocated_app_md5(std::string* app_md5) {
  if (app_md5 != nullptr) {
    
  } else {
    
  }
  _impl_.app_md5_.SetAllocated(app_md5, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.app_md5_.IsDefault()) {
    _impl_.app_md5_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:yy.protocol.core.C2SSecurityBody.app_md5)
}

// -------------------------------------------------------------------

// S2CSecurityBody

// .yy.protocol.core.S2CSecurityBody.ResultCode result_code = 1;
inline void S2CSecurityBody::clear_result_code() {
  _impl_.result_code_ = 0;
}
inline ::yy::protocol::core::S2CSecurityBody_ResultCode S2CSecurityBody::_internal_result_code() const {
  return static_cast< ::yy::protocol::core::S2CSecurityBody_ResultCode >(_impl_.result_code_);
}
inline ::yy::protocol::core::S2CSecurityBody_ResultCode S2CSecurityBody::result_code() const {
  // @@protoc_insertion_point(field_get:yy.protocol.core.S2CSecurityBody.result_code)
  return _internal_result_code();
}
inline void S2CSecurityBody::_internal_set_result_code(::yy::protocol::core::S2CSecurityBody_ResultCode value) {
  
  _impl_.result_code_ = value;
}
inline void S2CSecurityBody::set_result_code(::yy::protocol::core::S2CSecurityBody_ResultCode value) {
  _internal_set_result_code(value);
  // @@protoc_insertion_point(field_set:yy.protocol.core.S2CSecurityBody.result_code)
}

// optional uint32 server_udp_port = 2;
inline bool S2CSecurityBody::_internal_has_server_udp_port() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool S2CSecurityBody::has_server_udp_port() const {
  return _internal_has_server_udp_port();
}
inline void S2CSecurityBody::clear_server_udp_port() {
  _impl_.server_udp_port_ = 0u;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline uint32_t S2CSecurityBody::_internal_server_udp_port() const {
  return _impl_.server_udp_port_;
}
inline uint32_t S2CSecurityBody::server_udp_port() const {
  // @@protoc_insertion_point(field_get:yy.protocol.core.S2CSecurityBody.server_udp_port)
  return _internal_server_udp_port();
}
inline void S2CSecurityBody::_internal_set_server_udp_port(uint32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.server_udp_port_ = value;
}
inline void S2CSecurityBody::set_server_udp_port(uint32_t value) {
  _internal_set_server_udp_port(value);
  // @@protoc_insertion_point(field_set:yy.protocol.core.S2CSecurityBody.server_udp_port)
}

// optional uint64 session_id = 3;
inline bool S2CSecurityBody::_internal_has_session_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool S2CSecurityBody::has_session_id() const {
  return _internal_has_session_id();
}
inline void S2CSecurityBody::clear_session_id() {
  _impl_.session_id_ = uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline uint64_t S2CSecurityBody::_internal_session_id() const {
  return _impl_.session_id_;
}
inline uint64_t S2CSecurityBody::session_id() const {
  // @@protoc_insertion_point(field_get:yy.protocol.core.S2CSecurityBody.session_id)
  return _internal_session_id();
}
inline void S2CSecurityBody::_internal_set_session_id(uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.session_id_ = value;
}
inline void S2CSecurityBody::set_session_id(uint64_t value) {
  _internal_set_session_id(value);
  // @@protoc_insertion_point(field_set:yy.protocol.core.S2CSecurityBody.session_id)
}

// -------------------------------------------------------------------

// C2SUdpPortRegister

// uint64 session_id = 1;
inline void C2SUdpPortRegister::clear_session_id() {
  _impl_.session_id_ = uint64_t{0u};
}
inline uint64_t C2SUdpPortRegister::_internal_session_id() const {
  return _impl_.session_id_;
}
inline uint64_t C2SUdpPortRegister::session_id() const {
  // @@protoc_insertion_point(field_get:yy.protocol.core.C2SUdpPortRegister.session_id)
  return _internal_session_id();
}
inline void C2SUdpPortRegister::_internal_set_session_id(uint64_t value) {
  
  _impl_.session_id_ = value;
}
inline void C2SUdpPortRegister::set_session_id(uint64_t value) {
  _internal_set_session_id(value);
  // @@protoc_insertion_point(field_set:yy.protocol.core.C2SUdpPortRegister.session_id)
}

// string client_udp_ip = 2;
inline void C2SUdpPortRegister::clear_client_udp_ip() {
  _impl_.client_udp_ip_.ClearToEmpty();
}
inline const std::string& C2SUdpPortRegister::client_udp_ip() const {
  // @@protoc_insertion_point(field_get:yy.protocol.core.C2SUdpPortRegister.client_udp_ip)
  return _internal_client_udp_ip();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void C2SUdpPortRegister::set_client_udp_ip(ArgT0&& arg0, ArgT... args) {
 
 _impl_.client_udp_ip_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:yy.protocol.core.C2SUdpPortRegister.client_udp_ip)
}
inline std::string* C2SUdpPortRegister::mutable_client_udp_ip() {
  std::string* _s = _internal_mutable_client_udp_ip();
  // @@protoc_insertion_point(field_mutable:yy.protocol.core.C2SUdpPortRegister.client_udp_ip)
  return _s;
}
inline const std::string& C2SUdpPortRegister::_internal_client_udp_ip() const {
  return _impl_.client_udp_ip_.Get();
}
inline void C2SUdpPortRegister::_internal_set_client_udp_ip(const std::string& value) {
  
  _impl_.client_udp_ip_.Set(value, GetArenaForAllocation());
}
inline std::string* C2SUdpPortRegister::_internal_mutable_client_udp_ip() {
  
  return _impl_.client_udp_ip_.Mutable(GetArenaForAllocation());
}
inline std::string* C2SUdpPortRegister::release_client_udp_ip() {
  // @@protoc_insertion_point(field_release:yy.protocol.core.C2SUdpPortRegister.client_udp_ip)
  return _impl_.client_udp_ip_.Release();
}
inline void C2SUdpPortRegister::set_allocated_client_udp_ip(std::string* client_udp_ip) {
  if (client_udp_ip != nullptr) {
    
  } else {
    
  }
  _impl_.client_udp_ip_.SetAllocated(client_udp_ip, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.client_udp_ip_.IsDefault()) {
    _impl_.client_udp_ip_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:yy.protocol.core.C2SUdpPortRegister.client_udp_ip)
}

// uint32 client_udp_port = 3;
inline void C2SUdpPortRegister::clear_client_udp_port() {
  _impl_.client_udp_port_ = 0u;
}
inline uint32_t C2SUdpPortRegister::_internal_client_udp_port() const {
  return _impl_.client_udp_port_;
}
inline uint32_t C2SUdpPortRegister::client_udp_port() const {
  // @@protoc_insertion_point(field_get:yy.protocol.core.C2SUdpPortRegister.client_udp_port)
  return _internal_client_udp_port();
}
inline void C2SUdpPortRegister::_internal_set_client_udp_port(uint32_t value) {
  
  _impl_.client_udp_port_ = value;
}
inline void C2SUdpPortRegister::set_client_udp_port(uint32_t value) {
  _internal_set_client_udp_port(value);
  // @@protoc_insertion_point(field_set:yy.protocol.core.C2SUdpPortRegister.client_udp_port)
}

// -------------------------------------------------------------------

// S2CUdpPortRegister

// .yy.protocol.core.S2CUdpPortRegister.Status status = 1;
inline void S2CUdpPortRegister::clear_status() {
  _impl_.status_ = 0;
}
inline ::yy::protocol::core::S2CUdpPortRegister_Status S2CUdpPortRegister::_internal_status() const {
  return static_cast< ::yy::protocol::core::S2CUdpPortRegister_Status >(_impl_.status_);
}
inline ::yy::protocol::core::S2CUdpPortRegister_Status S2CUdpPortRegister::status() const {
  // @@protoc_insertion_point(field_get:yy.protocol.core.S2CUdpPortRegister.status)
  return _internal_status();
}
inline void S2CUdpPortRegister::_internal_set_status(::yy::protocol::core::S2CUdpPortRegister_Status value) {
  
  _impl_.status_ = value;
}
inline void S2CUdpPortRegister::set_status(::yy::protocol::core::S2CUdpPortRegister_Status value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:yy.protocol.core.S2CUdpPortRegister.status)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace core
}  // namespace protocol
}  // namespace yy

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::yy::protocol::core::S2CSecurityBody_ResultCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::yy::protocol::core::S2CSecurityBody_ResultCode>() {
  return ::yy::protocol::core::S2CSecurityBody_ResultCode_descriptor();
}
template <> struct is_proto_enum< ::yy::protocol::core::S2CUdpPortRegister_Status> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::yy::protocol::core::S2CUdpPortRegister_Status>() {
  return ::yy::protocol::core::S2CUdpPortRegister_Status_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_connection_2eproto
