// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_data.proto

#include "game_data.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace yy {
namespace protocol {
namespace app {
PROTOBUF_CONSTEXPR Vector3_net::Vector3_net(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.x_)*/0
  , /*decltype(_impl_.y_)*/0
  , /*decltype(_impl_.z_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Vector3_netDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Vector3_netDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Vector3_netDefaultTypeInternal() {}
  union {
    Vector3_net _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Vector3_netDefaultTypeInternal _Vector3_net_default_instance_;
PROTOBUF_CONSTEXPR Quaternion_net::Quaternion_net(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.x_)*/0
  , /*decltype(_impl_.y_)*/0
  , /*decltype(_impl_.z_)*/0
  , /*decltype(_impl_.w_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Quaternion_netDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Quaternion_netDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Quaternion_netDefaultTypeInternal() {}
  union {
    Quaternion_net _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Quaternion_netDefaultTypeInternal _Quaternion_net_default_instance_;
PROTOBUF_CONSTEXPR Transform_net::Transform_net(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.position_)*/nullptr
  , /*decltype(_impl_.rotation_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct Transform_netDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Transform_netDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~Transform_netDefaultTypeInternal() {}
  union {
    Transform_net _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Transform_netDefaultTypeInternal _Transform_net_default_instance_;
PROTOBUF_CONSTEXPR PlayerMove::PlayerMove(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.transform_)*/nullptr
  , /*decltype(_impl_.ani_speed_)*/0
  , /*decltype(_impl_.ani_motion_speed_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PlayerMoveDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlayerMoveDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlayerMoveDefaultTypeInternal() {}
  union {
    PlayerMove _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlayerMoveDefaultTypeInternal _PlayerMove_default_instance_;
PROTOBUF_CONSTEXPR PlayerJumpAndGravity::PlayerJumpAndGravity(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.ani_is_jump_)*/false
  , /*decltype(_impl_.ani_is_ground_)*/false
  , /*decltype(_impl_.ani_is_freefall_)*/false
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PlayerJumpAndGravityDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlayerJumpAndGravityDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlayerJumpAndGravityDefaultTypeInternal() {}
  union {
    PlayerJumpAndGravity _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlayerJumpAndGravityDefaultTypeInternal _PlayerJumpAndGravity_default_instance_;
PROTOBUF_CONSTEXPR PlayerBaseData::PlayerBaseData(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.account_data_)*/nullptr
  , /*decltype(_impl_.movement_)*/nullptr
  , /*decltype(_impl_.jump_and_gravity_)*/nullptr
  , /*decltype(_impl_.state_)*/0
  , /*decltype(_impl_.hp_current_)*/0
  , /*decltype(_impl_.hp_max_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct PlayerBaseDataDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PlayerBaseDataDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~PlayerBaseDataDefaultTypeInternal() {}
  union {
    PlayerBaseData _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PlayerBaseDataDefaultTypeInternal _PlayerBaseData_default_instance_;
}  // namespace app
}  // namespace protocol
}  // namespace yy
static ::_pb::Metadata file_level_metadata_game_5fdata_2eproto[6];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_game_5fdata_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_game_5fdata_2eproto = nullptr;

const uint32_t TableStruct_game_5fdata_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yy::protocol::app::Vector3_net, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yy::protocol::app::Vector3_net, _impl_.x_),
  PROTOBUF_FIELD_OFFSET(::yy::protocol::app::Vector3_net, _impl_.y_),
  PROTOBUF_FIELD_OFFSET(::yy::protocol::app::Vector3_net, _impl_.z_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yy::protocol::app::Quaternion_net, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yy::protocol::app::Quaternion_net, _impl_.x_),
  PROTOBUF_FIELD_OFFSET(::yy::protocol::app::Quaternion_net, _impl_.y_),
  PROTOBUF_FIELD_OFFSET(::yy::protocol::app::Quaternion_net, _impl_.z_),
  PROTOBUF_FIELD_OFFSET(::yy::protocol::app::Quaternion_net, _impl_.w_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yy::protocol::app::Transform_net, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yy::protocol::app::Transform_net, _impl_.position_),
  PROTOBUF_FIELD_OFFSET(::yy::protocol::app::Transform_net, _impl_.rotation_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yy::protocol::app::PlayerMove, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yy::protocol::app::PlayerMove, _impl_.transform_),
  PROTOBUF_FIELD_OFFSET(::yy::protocol::app::PlayerMove, _impl_.ani_speed_),
  PROTOBUF_FIELD_OFFSET(::yy::protocol::app::PlayerMove, _impl_.ani_motion_speed_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yy::protocol::app::PlayerJumpAndGravity, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yy::protocol::app::PlayerJumpAndGravity, _impl_.ani_is_jump_),
  PROTOBUF_FIELD_OFFSET(::yy::protocol::app::PlayerJumpAndGravity, _impl_.ani_is_ground_),
  PROTOBUF_FIELD_OFFSET(::yy::protocol::app::PlayerJumpAndGravity, _impl_.ani_is_freefall_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yy::protocol::app::PlayerBaseData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::yy::protocol::app::PlayerBaseData, _impl_.account_data_),
  PROTOBUF_FIELD_OFFSET(::yy::protocol::app::PlayerBaseData, _impl_.state_),
  PROTOBUF_FIELD_OFFSET(::yy::protocol::app::PlayerBaseData, _impl_.hp_current_),
  PROTOBUF_FIELD_OFFSET(::yy::protocol::app::PlayerBaseData, _impl_.hp_max_),
  PROTOBUF_FIELD_OFFSET(::yy::protocol::app::PlayerBaseData, _impl_.movement_),
  PROTOBUF_FIELD_OFFSET(::yy::protocol::app::PlayerBaseData, _impl_.jump_and_gravity_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::yy::protocol::app::Vector3_net)},
  { 9, -1, -1, sizeof(::yy::protocol::app::Quaternion_net)},
  { 19, -1, -1, sizeof(::yy::protocol::app::Transform_net)},
  { 27, -1, -1, sizeof(::yy::protocol::app::PlayerMove)},
  { 36, -1, -1, sizeof(::yy::protocol::app::PlayerJumpAndGravity)},
  { 45, -1, -1, sizeof(::yy::protocol::app::PlayerBaseData)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::yy::protocol::app::_Vector3_net_default_instance_._instance,
  &::yy::protocol::app::_Quaternion_net_default_instance_._instance,
  &::yy::protocol::app::_Transform_net_default_instance_._instance,
  &::yy::protocol::app::_PlayerMove_default_instance_._instance,
  &::yy::protocol::app::_PlayerJumpAndGravity_default_instance_._instance,
  &::yy::protocol::app::_PlayerBaseData_default_instance_._instance,
};

const char descriptor_table_protodef_game_5fdata_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\017game_data.proto\022\017yy.protocol.app\032\022acco"
  "unt_data.proto\".\n\013Vector3_net\022\t\n\001x\030\001 \001(\002"
  "\022\t\n\001y\030\002 \001(\002\022\t\n\001z\030\003 \001(\002\"<\n\016Quaternion_net"
  "\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\t\n\001z\030\003 \001(\002\022\t\n\001w\030\004"
  " \001(\002\"r\n\rTransform_net\022.\n\010position\030\002 \001(\0132"
  "\034.yy.protocol.app.Vector3_net\0221\n\010rotatio"
  "n\030\003 \001(\0132\037.yy.protocol.app.Quaternion_net"
  "\"l\n\nPlayerMove\0221\n\ttransform\030\001 \001(\0132\036.yy.p"
  "rotocol.app.Transform_net\022\021\n\tani_speed\030\005"
  " \001(\002\022\030\n\020ani_motion_speed\030\006 \001(\002\"[\n\024Player"
  "JumpAndGravity\022\023\n\013ani_is_jump\030\002 \001(\010\022\025\n\ra"
  "ni_is_ground\030\003 \001(\010\022\027\n\017ani_is_freefall\030\004 "
  "\001(\010\"\353\001\n\016PlayerBaseData\0226\n\014account_data\030\001"
  " \001(\0132 .yy.protocol.app.AccountBaseData\022\r"
  "\n\005state\030\003 \001(\005\022\022\n\nhp_current\030\004 \001(\005\022\016\n\006hp_"
  "max\030\005 \001(\005\022-\n\010movement\030\006 \001(\0132\033.yy.protoco"
  "l.app.PlayerMove\022\?\n\020jump_and_gravity\030\007 \001"
  "(\0132%.yy.protocol.app.PlayerJumpAndGravit"
  "yb\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_game_5fdata_2eproto_deps[1] = {
  &::descriptor_table_account_5fdata_2eproto,
};
static ::_pbi::once_flag descriptor_table_game_5fdata_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_game_5fdata_2eproto = {
    false, false, 729, descriptor_table_protodef_game_5fdata_2eproto,
    "game_data.proto",
    &descriptor_table_game_5fdata_2eproto_once, descriptor_table_game_5fdata_2eproto_deps, 1, 6,
    schemas, file_default_instances, TableStruct_game_5fdata_2eproto::offsets,
    file_level_metadata_game_5fdata_2eproto, file_level_enum_descriptors_game_5fdata_2eproto,
    file_level_service_descriptors_game_5fdata_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_game_5fdata_2eproto_getter() {
  return &descriptor_table_game_5fdata_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_game_5fdata_2eproto(&descriptor_table_game_5fdata_2eproto);
namespace yy {
namespace protocol {
namespace app {

// ===================================================================

class Vector3_net::_Internal {
 public:
};

Vector3_net::Vector3_net(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:yy.protocol.app.Vector3_net)
}
Vector3_net::Vector3_net(const Vector3_net& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Vector3_net* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.x_){}
    , decltype(_impl_.y_){}
    , decltype(_impl_.z_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.x_, &from._impl_.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.z_) -
    reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.z_));
  // @@protoc_insertion_point(copy_constructor:yy.protocol.app.Vector3_net)
}

inline void Vector3_net::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.x_){0}
    , decltype(_impl_.y_){0}
    , decltype(_impl_.z_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Vector3_net::~Vector3_net() {
  // @@protoc_insertion_point(destructor:yy.protocol.app.Vector3_net)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Vector3_net::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Vector3_net::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Vector3_net::Clear() {
// @@protoc_insertion_point(message_clear_start:yy.protocol.app.Vector3_net)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.z_) -
      reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.z_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Vector3_net::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // float x = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 13)) {
          _impl_.x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float y = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float z = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 29)) {
          _impl_.z_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Vector3_net::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yy.protocol.app.Vector3_net)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x = this->_internal_x();
  uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(1, this->_internal_x(), target);
  }

  // float y = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y = this->_internal_y();
  uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_y(), target);
  }

  // float z = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_z = this->_internal_z();
  uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(3, this->_internal_z(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yy.protocol.app.Vector3_net)
  return target;
}

size_t Vector3_net::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yy.protocol.app.Vector3_net)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float x = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x = this->_internal_x();
  uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    total_size += 1 + 4;
  }

  // float y = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y = this->_internal_y();
  uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    total_size += 1 + 4;
  }

  // float z = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_z = this->_internal_z();
  uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Vector3_net::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Vector3_net::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Vector3_net::GetClassData() const { return &_class_data_; }


void Vector3_net::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Vector3_net*>(&to_msg);
  auto& from = static_cast<const Vector3_net&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:yy.protocol.app.Vector3_net)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x = from._internal_x();
  uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    _this->_internal_set_x(from._internal_x());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y = from._internal_y();
  uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    _this->_internal_set_y(from._internal_y());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_z = from._internal_z();
  uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    _this->_internal_set_z(from._internal_z());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Vector3_net::CopyFrom(const Vector3_net& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yy.protocol.app.Vector3_net)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Vector3_net::IsInitialized() const {
  return true;
}

void Vector3_net::InternalSwap(Vector3_net* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Vector3_net, _impl_.z_)
      + sizeof(Vector3_net::_impl_.z_)
      - PROTOBUF_FIELD_OFFSET(Vector3_net, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Vector3_net::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_game_5fdata_2eproto_getter, &descriptor_table_game_5fdata_2eproto_once,
      file_level_metadata_game_5fdata_2eproto[0]);
}

// ===================================================================

class Quaternion_net::_Internal {
 public:
};

Quaternion_net::Quaternion_net(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:yy.protocol.app.Quaternion_net)
}
Quaternion_net::Quaternion_net(const Quaternion_net& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Quaternion_net* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.x_){}
    , decltype(_impl_.y_){}
    , decltype(_impl_.z_){}
    , decltype(_impl_.w_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.x_, &from._impl_.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.w_) -
    reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.w_));
  // @@protoc_insertion_point(copy_constructor:yy.protocol.app.Quaternion_net)
}

inline void Quaternion_net::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.x_){0}
    , decltype(_impl_.y_){0}
    , decltype(_impl_.z_){0}
    , decltype(_impl_.w_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Quaternion_net::~Quaternion_net() {
  // @@protoc_insertion_point(destructor:yy.protocol.app.Quaternion_net)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Quaternion_net::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Quaternion_net::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Quaternion_net::Clear() {
// @@protoc_insertion_point(message_clear_start:yy.protocol.app.Quaternion_net)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.w_) -
      reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.w_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Quaternion_net::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // float x = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 13)) {
          _impl_.x_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float y = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.y_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float z = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 29)) {
          _impl_.z_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float w = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 37)) {
          _impl_.w_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Quaternion_net::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yy.protocol.app.Quaternion_net)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // float x = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x = this->_internal_x();
  uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(1, this->_internal_x(), target);
  }

  // float y = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y = this->_internal_y();
  uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_y(), target);
  }

  // float z = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_z = this->_internal_z();
  uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(3, this->_internal_z(), target);
  }

  // float w = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_w = this->_internal_w();
  uint32_t raw_w;
  memcpy(&raw_w, &tmp_w, sizeof(tmp_w));
  if (raw_w != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(4, this->_internal_w(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yy.protocol.app.Quaternion_net)
  return target;
}

size_t Quaternion_net::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yy.protocol.app.Quaternion_net)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // float x = 1;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x = this->_internal_x();
  uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    total_size += 1 + 4;
  }

  // float y = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y = this->_internal_y();
  uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    total_size += 1 + 4;
  }

  // float z = 3;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_z = this->_internal_z();
  uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    total_size += 1 + 4;
  }

  // float w = 4;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_w = this->_internal_w();
  uint32_t raw_w;
  memcpy(&raw_w, &tmp_w, sizeof(tmp_w));
  if (raw_w != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Quaternion_net::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Quaternion_net::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Quaternion_net::GetClassData() const { return &_class_data_; }


void Quaternion_net::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Quaternion_net*>(&to_msg);
  auto& from = static_cast<const Quaternion_net&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:yy.protocol.app.Quaternion_net)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_x = from._internal_x();
  uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    _this->_internal_set_x(from._internal_x());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_y = from._internal_y();
  uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    _this->_internal_set_y(from._internal_y());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_z = from._internal_z();
  uint32_t raw_z;
  memcpy(&raw_z, &tmp_z, sizeof(tmp_z));
  if (raw_z != 0) {
    _this->_internal_set_z(from._internal_z());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_w = from._internal_w();
  uint32_t raw_w;
  memcpy(&raw_w, &tmp_w, sizeof(tmp_w));
  if (raw_w != 0) {
    _this->_internal_set_w(from._internal_w());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Quaternion_net::CopyFrom(const Quaternion_net& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yy.protocol.app.Quaternion_net)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Quaternion_net::IsInitialized() const {
  return true;
}

void Quaternion_net::InternalSwap(Quaternion_net* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Quaternion_net, _impl_.w_)
      + sizeof(Quaternion_net::_impl_.w_)
      - PROTOBUF_FIELD_OFFSET(Quaternion_net, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Quaternion_net::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_game_5fdata_2eproto_getter, &descriptor_table_game_5fdata_2eproto_once,
      file_level_metadata_game_5fdata_2eproto[1]);
}

// ===================================================================

class Transform_net::_Internal {
 public:
  static const ::yy::protocol::app::Vector3_net& position(const Transform_net* msg);
  static const ::yy::protocol::app::Quaternion_net& rotation(const Transform_net* msg);
};

const ::yy::protocol::app::Vector3_net&
Transform_net::_Internal::position(const Transform_net* msg) {
  return *msg->_impl_.position_;
}
const ::yy::protocol::app::Quaternion_net&
Transform_net::_Internal::rotation(const Transform_net* msg) {
  return *msg->_impl_.rotation_;
}
Transform_net::Transform_net(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:yy.protocol.app.Transform_net)
}
Transform_net::Transform_net(const Transform_net& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  Transform_net* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.position_){nullptr}
    , decltype(_impl_.rotation_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_position()) {
    _this->_impl_.position_ = new ::yy::protocol::app::Vector3_net(*from._impl_.position_);
  }
  if (from._internal_has_rotation()) {
    _this->_impl_.rotation_ = new ::yy::protocol::app::Quaternion_net(*from._impl_.rotation_);
  }
  // @@protoc_insertion_point(copy_constructor:yy.protocol.app.Transform_net)
}

inline void Transform_net::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.position_){nullptr}
    , decltype(_impl_.rotation_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

Transform_net::~Transform_net() {
  // @@protoc_insertion_point(destructor:yy.protocol.app.Transform_net)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void Transform_net::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.position_;
  if (this != internal_default_instance()) delete _impl_.rotation_;
}

void Transform_net::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void Transform_net::Clear() {
// @@protoc_insertion_point(message_clear_start:yy.protocol.app.Transform_net)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.position_ != nullptr) {
    delete _impl_.position_;
  }
  _impl_.position_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.rotation_ != nullptr) {
    delete _impl_.rotation_;
  }
  _impl_.rotation_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Transform_net::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .yy.protocol.app.Vector3_net position = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_position(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .yy.protocol.app.Quaternion_net rotation = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_rotation(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Transform_net::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yy.protocol.app.Transform_net)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .yy.protocol.app.Vector3_net position = 2;
  if (this->_internal_has_position()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::position(this),
        _Internal::position(this).GetCachedSize(), target, stream);
  }

  // .yy.protocol.app.Quaternion_net rotation = 3;
  if (this->_internal_has_rotation()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::rotation(this),
        _Internal::rotation(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yy.protocol.app.Transform_net)
  return target;
}

size_t Transform_net::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yy.protocol.app.Transform_net)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .yy.protocol.app.Vector3_net position = 2;
  if (this->_internal_has_position()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.position_);
  }

  // .yy.protocol.app.Quaternion_net rotation = 3;
  if (this->_internal_has_rotation()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.rotation_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Transform_net::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    Transform_net::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Transform_net::GetClassData() const { return &_class_data_; }


void Transform_net::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<Transform_net*>(&to_msg);
  auto& from = static_cast<const Transform_net&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:yy.protocol.app.Transform_net)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_position()) {
    _this->_internal_mutable_position()->::yy::protocol::app::Vector3_net::MergeFrom(
        from._internal_position());
  }
  if (from._internal_has_rotation()) {
    _this->_internal_mutable_rotation()->::yy::protocol::app::Quaternion_net::MergeFrom(
        from._internal_rotation());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Transform_net::CopyFrom(const Transform_net& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yy.protocol.app.Transform_net)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Transform_net::IsInitialized() const {
  return true;
}

void Transform_net::InternalSwap(Transform_net* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Transform_net, _impl_.rotation_)
      + sizeof(Transform_net::_impl_.rotation_)
      - PROTOBUF_FIELD_OFFSET(Transform_net, _impl_.position_)>(
          reinterpret_cast<char*>(&_impl_.position_),
          reinterpret_cast<char*>(&other->_impl_.position_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Transform_net::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_game_5fdata_2eproto_getter, &descriptor_table_game_5fdata_2eproto_once,
      file_level_metadata_game_5fdata_2eproto[2]);
}

// ===================================================================

class PlayerMove::_Internal {
 public:
  static const ::yy::protocol::app::Transform_net& transform(const PlayerMove* msg);
};

const ::yy::protocol::app::Transform_net&
PlayerMove::_Internal::transform(const PlayerMove* msg) {
  return *msg->_impl_.transform_;
}
PlayerMove::PlayerMove(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:yy.protocol.app.PlayerMove)
}
PlayerMove::PlayerMove(const PlayerMove& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PlayerMove* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.transform_){nullptr}
    , decltype(_impl_.ani_speed_){}
    , decltype(_impl_.ani_motion_speed_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_transform()) {
    _this->_impl_.transform_ = new ::yy::protocol::app::Transform_net(*from._impl_.transform_);
  }
  ::memcpy(&_impl_.ani_speed_, &from._impl_.ani_speed_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.ani_motion_speed_) -
    reinterpret_cast<char*>(&_impl_.ani_speed_)) + sizeof(_impl_.ani_motion_speed_));
  // @@protoc_insertion_point(copy_constructor:yy.protocol.app.PlayerMove)
}

inline void PlayerMove::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.transform_){nullptr}
    , decltype(_impl_.ani_speed_){0}
    , decltype(_impl_.ani_motion_speed_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PlayerMove::~PlayerMove() {
  // @@protoc_insertion_point(destructor:yy.protocol.app.PlayerMove)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PlayerMove::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.transform_;
}

void PlayerMove::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PlayerMove::Clear() {
// @@protoc_insertion_point(message_clear_start:yy.protocol.app.PlayerMove)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.transform_ != nullptr) {
    delete _impl_.transform_;
  }
  _impl_.transform_ = nullptr;
  ::memset(&_impl_.ani_speed_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.ani_motion_speed_) -
      reinterpret_cast<char*>(&_impl_.ani_speed_)) + sizeof(_impl_.ani_motion_speed_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PlayerMove::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .yy.protocol.app.Transform_net transform = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_transform(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // float ani_speed = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 45)) {
          _impl_.ani_speed_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // float ani_motion_speed = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 53)) {
          _impl_.ani_motion_speed_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PlayerMove::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yy.protocol.app.PlayerMove)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .yy.protocol.app.Transform_net transform = 1;
  if (this->_internal_has_transform()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::transform(this),
        _Internal::transform(this).GetCachedSize(), target, stream);
  }

  // float ani_speed = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_ani_speed = this->_internal_ani_speed();
  uint32_t raw_ani_speed;
  memcpy(&raw_ani_speed, &tmp_ani_speed, sizeof(tmp_ani_speed));
  if (raw_ani_speed != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(5, this->_internal_ani_speed(), target);
  }

  // float ani_motion_speed = 6;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_ani_motion_speed = this->_internal_ani_motion_speed();
  uint32_t raw_ani_motion_speed;
  memcpy(&raw_ani_motion_speed, &tmp_ani_motion_speed, sizeof(tmp_ani_motion_speed));
  if (raw_ani_motion_speed != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(6, this->_internal_ani_motion_speed(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yy.protocol.app.PlayerMove)
  return target;
}

size_t PlayerMove::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yy.protocol.app.PlayerMove)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .yy.protocol.app.Transform_net transform = 1;
  if (this->_internal_has_transform()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.transform_);
  }

  // float ani_speed = 5;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_ani_speed = this->_internal_ani_speed();
  uint32_t raw_ani_speed;
  memcpy(&raw_ani_speed, &tmp_ani_speed, sizeof(tmp_ani_speed));
  if (raw_ani_speed != 0) {
    total_size += 1 + 4;
  }

  // float ani_motion_speed = 6;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_ani_motion_speed = this->_internal_ani_motion_speed();
  uint32_t raw_ani_motion_speed;
  memcpy(&raw_ani_motion_speed, &tmp_ani_motion_speed, sizeof(tmp_ani_motion_speed));
  if (raw_ani_motion_speed != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PlayerMove::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PlayerMove::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PlayerMove::GetClassData() const { return &_class_data_; }


void PlayerMove::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PlayerMove*>(&to_msg);
  auto& from = static_cast<const PlayerMove&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:yy.protocol.app.PlayerMove)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_transform()) {
    _this->_internal_mutable_transform()->::yy::protocol::app::Transform_net::MergeFrom(
        from._internal_transform());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_ani_speed = from._internal_ani_speed();
  uint32_t raw_ani_speed;
  memcpy(&raw_ani_speed, &tmp_ani_speed, sizeof(tmp_ani_speed));
  if (raw_ani_speed != 0) {
    _this->_internal_set_ani_speed(from._internal_ani_speed());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_ani_motion_speed = from._internal_ani_motion_speed();
  uint32_t raw_ani_motion_speed;
  memcpy(&raw_ani_motion_speed, &tmp_ani_motion_speed, sizeof(tmp_ani_motion_speed));
  if (raw_ani_motion_speed != 0) {
    _this->_internal_set_ani_motion_speed(from._internal_ani_motion_speed());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PlayerMove::CopyFrom(const PlayerMove& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yy.protocol.app.PlayerMove)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerMove::IsInitialized() const {
  return true;
}

void PlayerMove::InternalSwap(PlayerMove* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PlayerMove, _impl_.ani_motion_speed_)
      + sizeof(PlayerMove::_impl_.ani_motion_speed_)
      - PROTOBUF_FIELD_OFFSET(PlayerMove, _impl_.transform_)>(
          reinterpret_cast<char*>(&_impl_.transform_),
          reinterpret_cast<char*>(&other->_impl_.transform_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PlayerMove::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_game_5fdata_2eproto_getter, &descriptor_table_game_5fdata_2eproto_once,
      file_level_metadata_game_5fdata_2eproto[3]);
}

// ===================================================================

class PlayerJumpAndGravity::_Internal {
 public:
};

PlayerJumpAndGravity::PlayerJumpAndGravity(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:yy.protocol.app.PlayerJumpAndGravity)
}
PlayerJumpAndGravity::PlayerJumpAndGravity(const PlayerJumpAndGravity& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PlayerJumpAndGravity* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.ani_is_jump_){}
    , decltype(_impl_.ani_is_ground_){}
    , decltype(_impl_.ani_is_freefall_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&_impl_.ani_is_jump_, &from._impl_.ani_is_jump_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.ani_is_freefall_) -
    reinterpret_cast<char*>(&_impl_.ani_is_jump_)) + sizeof(_impl_.ani_is_freefall_));
  // @@protoc_insertion_point(copy_constructor:yy.protocol.app.PlayerJumpAndGravity)
}

inline void PlayerJumpAndGravity::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.ani_is_jump_){false}
    , decltype(_impl_.ani_is_ground_){false}
    , decltype(_impl_.ani_is_freefall_){false}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PlayerJumpAndGravity::~PlayerJumpAndGravity() {
  // @@protoc_insertion_point(destructor:yy.protocol.app.PlayerJumpAndGravity)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PlayerJumpAndGravity::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void PlayerJumpAndGravity::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PlayerJumpAndGravity::Clear() {
// @@protoc_insertion_point(message_clear_start:yy.protocol.app.PlayerJumpAndGravity)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.ani_is_jump_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.ani_is_freefall_) -
      reinterpret_cast<char*>(&_impl_.ani_is_jump_)) + sizeof(_impl_.ani_is_freefall_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PlayerJumpAndGravity::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // bool ani_is_jump = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.ani_is_jump_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool ani_is_ground = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.ani_is_ground_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bool ani_is_freefall = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.ani_is_freefall_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PlayerJumpAndGravity::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yy.protocol.app.PlayerJumpAndGravity)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // bool ani_is_jump = 2;
  if (this->_internal_ani_is_jump() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(2, this->_internal_ani_is_jump(), target);
  }

  // bool ani_is_ground = 3;
  if (this->_internal_ani_is_ground() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(3, this->_internal_ani_is_ground(), target);
  }

  // bool ani_is_freefall = 4;
  if (this->_internal_ani_is_freefall() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(4, this->_internal_ani_is_freefall(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yy.protocol.app.PlayerJumpAndGravity)
  return target;
}

size_t PlayerJumpAndGravity::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yy.protocol.app.PlayerJumpAndGravity)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool ani_is_jump = 2;
  if (this->_internal_ani_is_jump() != 0) {
    total_size += 1 + 1;
  }

  // bool ani_is_ground = 3;
  if (this->_internal_ani_is_ground() != 0) {
    total_size += 1 + 1;
  }

  // bool ani_is_freefall = 4;
  if (this->_internal_ani_is_freefall() != 0) {
    total_size += 1 + 1;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PlayerJumpAndGravity::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PlayerJumpAndGravity::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PlayerJumpAndGravity::GetClassData() const { return &_class_data_; }


void PlayerJumpAndGravity::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PlayerJumpAndGravity*>(&to_msg);
  auto& from = static_cast<const PlayerJumpAndGravity&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:yy.protocol.app.PlayerJumpAndGravity)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_ani_is_jump() != 0) {
    _this->_internal_set_ani_is_jump(from._internal_ani_is_jump());
  }
  if (from._internal_ani_is_ground() != 0) {
    _this->_internal_set_ani_is_ground(from._internal_ani_is_ground());
  }
  if (from._internal_ani_is_freefall() != 0) {
    _this->_internal_set_ani_is_freefall(from._internal_ani_is_freefall());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PlayerJumpAndGravity::CopyFrom(const PlayerJumpAndGravity& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yy.protocol.app.PlayerJumpAndGravity)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerJumpAndGravity::IsInitialized() const {
  return true;
}

void PlayerJumpAndGravity::InternalSwap(PlayerJumpAndGravity* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PlayerJumpAndGravity, _impl_.ani_is_freefall_)
      + sizeof(PlayerJumpAndGravity::_impl_.ani_is_freefall_)
      - PROTOBUF_FIELD_OFFSET(PlayerJumpAndGravity, _impl_.ani_is_jump_)>(
          reinterpret_cast<char*>(&_impl_.ani_is_jump_),
          reinterpret_cast<char*>(&other->_impl_.ani_is_jump_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PlayerJumpAndGravity::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_game_5fdata_2eproto_getter, &descriptor_table_game_5fdata_2eproto_once,
      file_level_metadata_game_5fdata_2eproto[4]);
}

// ===================================================================

class PlayerBaseData::_Internal {
 public:
  static const ::yy::protocol::app::AccountBaseData& account_data(const PlayerBaseData* msg);
  static const ::yy::protocol::app::PlayerMove& movement(const PlayerBaseData* msg);
  static const ::yy::protocol::app::PlayerJumpAndGravity& jump_and_gravity(const PlayerBaseData* msg);
};

const ::yy::protocol::app::AccountBaseData&
PlayerBaseData::_Internal::account_data(const PlayerBaseData* msg) {
  return *msg->_impl_.account_data_;
}
const ::yy::protocol::app::PlayerMove&
PlayerBaseData::_Internal::movement(const PlayerBaseData* msg) {
  return *msg->_impl_.movement_;
}
const ::yy::protocol::app::PlayerJumpAndGravity&
PlayerBaseData::_Internal::jump_and_gravity(const PlayerBaseData* msg) {
  return *msg->_impl_.jump_and_gravity_;
}
void PlayerBaseData::clear_account_data() {
  if (GetArenaForAllocation() == nullptr && _impl_.account_data_ != nullptr) {
    delete _impl_.account_data_;
  }
  _impl_.account_data_ = nullptr;
}
PlayerBaseData::PlayerBaseData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:yy.protocol.app.PlayerBaseData)
}
PlayerBaseData::PlayerBaseData(const PlayerBaseData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  PlayerBaseData* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.account_data_){nullptr}
    , decltype(_impl_.movement_){nullptr}
    , decltype(_impl_.jump_and_gravity_){nullptr}
    , decltype(_impl_.state_){}
    , decltype(_impl_.hp_current_){}
    , decltype(_impl_.hp_max_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_account_data()) {
    _this->_impl_.account_data_ = new ::yy::protocol::app::AccountBaseData(*from._impl_.account_data_);
  }
  if (from._internal_has_movement()) {
    _this->_impl_.movement_ = new ::yy::protocol::app::PlayerMove(*from._impl_.movement_);
  }
  if (from._internal_has_jump_and_gravity()) {
    _this->_impl_.jump_and_gravity_ = new ::yy::protocol::app::PlayerJumpAndGravity(*from._impl_.jump_and_gravity_);
  }
  ::memcpy(&_impl_.state_, &from._impl_.state_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.hp_max_) -
    reinterpret_cast<char*>(&_impl_.state_)) + sizeof(_impl_.hp_max_));
  // @@protoc_insertion_point(copy_constructor:yy.protocol.app.PlayerBaseData)
}

inline void PlayerBaseData::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.account_data_){nullptr}
    , decltype(_impl_.movement_){nullptr}
    , decltype(_impl_.jump_and_gravity_){nullptr}
    , decltype(_impl_.state_){0}
    , decltype(_impl_.hp_current_){0}
    , decltype(_impl_.hp_max_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

PlayerBaseData::~PlayerBaseData() {
  // @@protoc_insertion_point(destructor:yy.protocol.app.PlayerBaseData)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void PlayerBaseData::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.account_data_;
  if (this != internal_default_instance()) delete _impl_.movement_;
  if (this != internal_default_instance()) delete _impl_.jump_and_gravity_;
}

void PlayerBaseData::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void PlayerBaseData::Clear() {
// @@protoc_insertion_point(message_clear_start:yy.protocol.app.PlayerBaseData)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.account_data_ != nullptr) {
    delete _impl_.account_data_;
  }
  _impl_.account_data_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.movement_ != nullptr) {
    delete _impl_.movement_;
  }
  _impl_.movement_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.jump_and_gravity_ != nullptr) {
    delete _impl_.jump_and_gravity_;
  }
  _impl_.jump_and_gravity_ = nullptr;
  ::memset(&_impl_.state_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.hp_max_) -
      reinterpret_cast<char*>(&_impl_.state_)) + sizeof(_impl_.hp_max_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PlayerBaseData::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .yy.protocol.app.AccountBaseData account_data = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_account_data(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 state = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.state_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 hp_current = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.hp_current_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 hp_max = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.hp_max_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .yy.protocol.app.PlayerMove movement = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_movement(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .yy.protocol.app.PlayerJumpAndGravity jump_and_gravity = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 58)) {
          ptr = ctx->ParseMessage(_internal_mutable_jump_and_gravity(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* PlayerBaseData::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yy.protocol.app.PlayerBaseData)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .yy.protocol.app.AccountBaseData account_data = 1;
  if (this->_internal_has_account_data()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::account_data(this),
        _Internal::account_data(this).GetCachedSize(), target, stream);
  }

  // int32 state = 3;
  if (this->_internal_state() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(3, this->_internal_state(), target);
  }

  // int32 hp_current = 4;
  if (this->_internal_hp_current() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(4, this->_internal_hp_current(), target);
  }

  // int32 hp_max = 5;
  if (this->_internal_hp_max() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(5, this->_internal_hp_max(), target);
  }

  // .yy.protocol.app.PlayerMove movement = 6;
  if (this->_internal_has_movement()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(6, _Internal::movement(this),
        _Internal::movement(this).GetCachedSize(), target, stream);
  }

  // .yy.protocol.app.PlayerJumpAndGravity jump_and_gravity = 7;
  if (this->_internal_has_jump_and_gravity()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(7, _Internal::jump_and_gravity(this),
        _Internal::jump_and_gravity(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yy.protocol.app.PlayerBaseData)
  return target;
}

size_t PlayerBaseData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yy.protocol.app.PlayerBaseData)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .yy.protocol.app.AccountBaseData account_data = 1;
  if (this->_internal_has_account_data()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.account_data_);
  }

  // .yy.protocol.app.PlayerMove movement = 6;
  if (this->_internal_has_movement()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.movement_);
  }

  // .yy.protocol.app.PlayerJumpAndGravity jump_and_gravity = 7;
  if (this->_internal_has_jump_and_gravity()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.jump_and_gravity_);
  }

  // int32 state = 3;
  if (this->_internal_state() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_state());
  }

  // int32 hp_current = 4;
  if (this->_internal_hp_current() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_hp_current());
  }

  // int32 hp_max = 5;
  if (this->_internal_hp_max() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_hp_max());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData PlayerBaseData::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    PlayerBaseData::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*PlayerBaseData::GetClassData() const { return &_class_data_; }


void PlayerBaseData::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<PlayerBaseData*>(&to_msg);
  auto& from = static_cast<const PlayerBaseData&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:yy.protocol.app.PlayerBaseData)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_account_data()) {
    _this->_internal_mutable_account_data()->::yy::protocol::app::AccountBaseData::MergeFrom(
        from._internal_account_data());
  }
  if (from._internal_has_movement()) {
    _this->_internal_mutable_movement()->::yy::protocol::app::PlayerMove::MergeFrom(
        from._internal_movement());
  }
  if (from._internal_has_jump_and_gravity()) {
    _this->_internal_mutable_jump_and_gravity()->::yy::protocol::app::PlayerJumpAndGravity::MergeFrom(
        from._internal_jump_and_gravity());
  }
  if (from._internal_state() != 0) {
    _this->_internal_set_state(from._internal_state());
  }
  if (from._internal_hp_current() != 0) {
    _this->_internal_set_hp_current(from._internal_hp_current());
  }
  if (from._internal_hp_max() != 0) {
    _this->_internal_set_hp_max(from._internal_hp_max());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void PlayerBaseData::CopyFrom(const PlayerBaseData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yy.protocol.app.PlayerBaseData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerBaseData::IsInitialized() const {
  return true;
}

void PlayerBaseData::InternalSwap(PlayerBaseData* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PlayerBaseData, _impl_.hp_max_)
      + sizeof(PlayerBaseData::_impl_.hp_max_)
      - PROTOBUF_FIELD_OFFSET(PlayerBaseData, _impl_.account_data_)>(
          reinterpret_cast<char*>(&_impl_.account_data_),
          reinterpret_cast<char*>(&other->_impl_.account_data_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PlayerBaseData::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_game_5fdata_2eproto_getter, &descriptor_table_game_5fdata_2eproto_once,
      file_level_metadata_game_5fdata_2eproto[5]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace app
}  // namespace protocol
}  // namespace yy
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::yy::protocol::app::Vector3_net*
Arena::CreateMaybeMessage< ::yy::protocol::app::Vector3_net >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yy::protocol::app::Vector3_net >(arena);
}
template<> PROTOBUF_NOINLINE ::yy::protocol::app::Quaternion_net*
Arena::CreateMaybeMessage< ::yy::protocol::app::Quaternion_net >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yy::protocol::app::Quaternion_net >(arena);
}
template<> PROTOBUF_NOINLINE ::yy::protocol::app::Transform_net*
Arena::CreateMaybeMessage< ::yy::protocol::app::Transform_net >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yy::protocol::app::Transform_net >(arena);
}
template<> PROTOBUF_NOINLINE ::yy::protocol::app::PlayerMove*
Arena::CreateMaybeMessage< ::yy::protocol::app::PlayerMove >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yy::protocol::app::PlayerMove >(arena);
}
template<> PROTOBUF_NOINLINE ::yy::protocol::app::PlayerJumpAndGravity*
Arena::CreateMaybeMessage< ::yy::protocol::app::PlayerJumpAndGravity >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yy::protocol::app::PlayerJumpAndGravity >(arena);
}
template<> PROTOBUF_NOINLINE ::yy::protocol::app::PlayerBaseData*
Arena::CreateMaybeMessage< ::yy::protocol::app::PlayerBaseData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yy::protocol::app::PlayerBaseData >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
