// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_cmd.proto

#include "msg_cmd.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace yy {
namespace protocol {
}  // namespace protocol
}  // namespace yy
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_msg_5fcmd_2eproto[1];
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_msg_5fcmd_2eproto = nullptr;
const uint32_t TableStruct_msg_5fcmd_2eproto::offsets[1] = {};
static constexpr ::_pbi::MigrationSchema* schemas = nullptr;
static constexpr ::_pb::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_msg_5fcmd_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rmsg_cmd.proto\022\013yy.protocol*\256\010\n\016Message"
  "Command\022\017\n\013MSG_Unknown\020\000\022\022\n\rMSG_HeartBod"
  "y\020\364\003\022\023\n\016MSG_XorBodyRsp\020\365\003\022\031\n\024MSG_Securit"
  "yCheckReq\020\366\003\022\031\n\024MSG_SecurityCheckRsp\020\367\003\022"
  "\033\n\026MSG_UdpPortRegisterReq\020\370\003\022\033\n\026MSG_UdpP"
  "ortRegisterRsp\020\371\003\022\021\n\014MSG_LoginReq\020\350\007\022\021\n\014"
  "MSG_LoginRsp\020\351\007\022\024\n\017MSG_RegisterReq\020\352\007\022\024\n"
  "\017MSG_RegisterRsp\020\353\007\022\025\n\020MSG_QuitLoginReq\020"
  "\354\007\022\025\n\020MSG_QuitLoginRsp\020\355\007\022\026\n\021MSG_CreateR"
  "oomReq\020\320\017\022\026\n\021MSG_CreateRoomRsp\020\321\017\022\026\n\021MSG"
  "_SearchRoomReq\020\322\017\022\026\n\021MSG_SearchRoomRsp\020\323"
  "\017\022\030\n\023MSG_SelfJoinRoomReq\020\324\017\022\030\n\023MSG_SelfJ"
  "oinRoomRsp\020\325\017\022\030\n\023MSG_SelfQuitRoomReq\020\326\017\022"
  "\030\n\023MSG_SelfQuitRoomRsp\020\327\017\022\031\n\024MSG_OtherJo"
  "inRoomRsp\020\330\017\022\031\n\024MSG_OtherQuitRoomRsp\020\331\017\022"
  "\036\n\031MSG_GetEnterSceneTokenReq\020\332\017\022\036\n\031MSG_G"
  "etEnterSceneTokenRsp\020\333\017\022\031\n\024MSG_Broadcast"
  "RoomReq\020\374\021\022\031\n\024MSG_BroadcastRoomRsp\020\375\021\022\023\n"
  "\016MSG_NewRoomReq\020\304\023\022\023\n\016MSG_NewRoomRsp\020\305\023\022"
  "\026\n\021MSG_DeleteRoomReq\020\307\023\022\026\n\021MSG_DeleteRoo"
  "mRsp\020\310\023\022\026\n\021MSG_SceneLoginReq\020\270\027\022\026\n\021MSG_S"
  "ceneLoginRsp\020\271\027\022\026\n\021MSG_C2SEnterScene\020\272\027\022"
  "\026\n\021MSG_S2CEnterScene\020\273\027\022\026\n\021MSG_C2SLeaveS"
  "cene\020\274\027\022\026\n\021MSG_S2CLeaveScene\020\275\027\022\020\n\013MSG_C"
  "2SMove\020\276\027\022\020\n\013MSG_S2CMove\020\277\027\022\032\n\025MSG_C2SJu"
  "mpAndGravity\020\300\027\022\032\n\025MSG_S2CJumpAndGravity"
  "\020\301\027\022\033\n\026MSG_C2SOtherPlayerData\020\302\027\022\033\n\026MSG_"
  "S2COtherPlayerData\020\303\027b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_msg_5fcmd_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_msg_5fcmd_2eproto = {
    false, false, 1109, descriptor_table_protodef_msg_5fcmd_2eproto,
    "msg_cmd.proto",
    &descriptor_table_msg_5fcmd_2eproto_once, nullptr, 0, 0,
    schemas, file_default_instances, TableStruct_msg_5fcmd_2eproto::offsets,
    nullptr, file_level_enum_descriptors_msg_5fcmd_2eproto,
    file_level_service_descriptors_msg_5fcmd_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_msg_5fcmd_2eproto_getter() {
  return &descriptor_table_msg_5fcmd_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_msg_5fcmd_2eproto(&descriptor_table_msg_5fcmd_2eproto);
namespace yy {
namespace protocol {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MessageCommand_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_msg_5fcmd_2eproto);
  return file_level_enum_descriptors_msg_5fcmd_2eproto[0];
}
bool MessageCommand_IsValid(int value) {
  switch (value) {
    case 0:
    case 500:
    case 501:
    case 502:
    case 503:
    case 504:
    case 505:
    case 1000:
    case 1001:
    case 1002:
    case 1003:
    case 1004:
    case 1005:
    case 2000:
    case 2001:
    case 2002:
    case 2003:
    case 2004:
    case 2005:
    case 2006:
    case 2007:
    case 2008:
    case 2009:
    case 2010:
    case 2011:
    case 2300:
    case 2301:
    case 2500:
    case 2501:
    case 2503:
    case 2504:
    case 3000:
    case 3001:
    case 3002:
    case 3003:
    case 3004:
    case 3005:
    case 3006:
    case 3007:
    case 3008:
    case 3009:
    case 3010:
    case 3011:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protocol
}  // namespace yy
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
