// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player.proto

#include "player.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_player_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_PlayerBaseData_player_2eproto;
namespace yy {
namespace app {
namespace protocol {
class PlayerIDDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<PlayerID> _instance;
} _PlayerID_default_instance_;
class PlayerBaseDataDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<PlayerBaseData> _instance;
} _PlayerBaseData_default_instance_;
class PlayerMoveDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<PlayerMove> _instance;
} _PlayerMove_default_instance_;
class PlayerJumpAndGravityDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<PlayerJumpAndGravity> _instance;
} _PlayerJumpAndGravity_default_instance_;
class LoginResponseDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<LoginResponse> _instance;
} _LoginResponse_default_instance_;
}  // namespace protocol
}  // namespace app
}  // namespace yy
static void InitDefaultsscc_info_LoginResponse_player_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::yy::app::protocol::_LoginResponse_default_instance_;
    new (ptr) ::yy::app::protocol::LoginResponse();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::yy::app::protocol::LoginResponse::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_LoginResponse_player_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_LoginResponse_player_2eproto}, {
      &scc_info_PlayerBaseData_player_2eproto.base,}};

static void InitDefaultsscc_info_PlayerBaseData_player_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::yy::app::protocol::_PlayerBaseData_default_instance_;
    new (ptr) ::yy::app::protocol::PlayerBaseData();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::yy::app::protocol::PlayerBaseData::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_PlayerBaseData_player_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_PlayerBaseData_player_2eproto}, {}};

static void InitDefaultsscc_info_PlayerID_player_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::yy::app::protocol::_PlayerID_default_instance_;
    new (ptr) ::yy::app::protocol::PlayerID();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::yy::app::protocol::PlayerID::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_PlayerID_player_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_PlayerID_player_2eproto}, {}};

static void InitDefaultsscc_info_PlayerJumpAndGravity_player_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::yy::app::protocol::_PlayerJumpAndGravity_default_instance_;
    new (ptr) ::yy::app::protocol::PlayerJumpAndGravity();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::yy::app::protocol::PlayerJumpAndGravity::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_PlayerJumpAndGravity_player_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_PlayerJumpAndGravity_player_2eproto}, {}};

static void InitDefaultsscc_info_PlayerMove_player_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::yy::app::protocol::_PlayerMove_default_instance_;
    new (ptr) ::yy::app::protocol::PlayerMove();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::yy::app::protocol::PlayerMove::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_PlayerMove_player_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_PlayerMove_player_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_player_2eproto[5];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_player_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_player_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_player_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::PlayerID, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::PlayerID, uid_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::PlayerBaseData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::PlayerBaseData, uid_),
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::PlayerBaseData, sockfd_),
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::PlayerBaseData, state_),
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::PlayerBaseData, hp_current_),
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::PlayerBaseData, hp_max_),
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::PlayerBaseData, position_),
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::PlayerBaseData, rotation_),
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::PlayerBaseData, ani_speed_),
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::PlayerBaseData, ani_isjump_),
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::PlayerBaseData, ani_isground_),
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::PlayerBaseData, ani_isfreefall_),
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::PlayerBaseData, ani_motionspeed_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::PlayerMove, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::PlayerMove, uid_),
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::PlayerMove, position_),
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::PlayerMove, rotation_),
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::PlayerMove, move_target_),
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::PlayerMove, ani_speed_),
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::PlayerMove, ani_motionspeed_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::PlayerJumpAndGravity, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::PlayerJumpAndGravity, uid_),
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::PlayerJumpAndGravity, ani_isjump_),
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::PlayerJumpAndGravity, ani_isground_),
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::PlayerJumpAndGravity, ani_isfreefall_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::LoginResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::LoginResponse, result_),
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::LoginResponse, selfdata_),
  PROTOBUF_FIELD_OFFSET(::yy::app::protocol::LoginResponse, othersdata_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::yy::app::protocol::PlayerID)},
  { 6, -1, sizeof(::yy::app::protocol::PlayerBaseData)},
  { 23, -1, sizeof(::yy::app::protocol::PlayerMove)},
  { 34, -1, sizeof(::yy::app::protocol::PlayerJumpAndGravity)},
  { 43, -1, sizeof(::yy::app::protocol::LoginResponse)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::yy::app::protocol::_PlayerID_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::yy::app::protocol::_PlayerBaseData_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::yy::app::protocol::_PlayerMove_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::yy::app::protocol::_PlayerJumpAndGravity_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::yy::app::protocol::_LoginResponse_default_instance_),
};

const char descriptor_table_protodef_player_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014player.proto\022\017yy.app.protocol\"\027\n\010Playe"
  "rID\022\013\n\003uid\030\001 \001(\r\"\362\001\n\016PlayerBaseData\022\013\n\003u"
  "id\030\001 \001(\r\022\016\n\006sockfd\030\002 \001(\005\022\r\n\005state\030\003 \001(\005\022"
  "\022\n\nhp_current\030\004 \001(\005\022\016\n\006hp_max\030\005 \001(\005\022\020\n\010p"
  "osition\030\006 \001(\014\022\020\n\010rotation\030\007 \001(\014\022\021\n\tani_s"
  "peed\030\010 \001(\002\022\022\n\nani_isJump\030\t \001(\010\022\024\n\014ani_is"
  "Ground\030\n \001(\010\022\026\n\016ani_isFreeFall\030\013 \001(\010\022\027\n\017"
  "ani_motionSpeed\030\014 \001(\002\"~\n\nPlayerMove\022\013\n\003u"
  "id\030\001 \001(\r\022\020\n\010position\030\002 \001(\014\022\020\n\010rotation\030\003"
  " \001(\014\022\023\n\013move_target\030\004 \001(\014\022\021\n\tani_speed\030\005"
  " \001(\002\022\027\n\017ani_motionSpeed\030\006 \001(\002\"e\n\024PlayerJ"
  "umpAndGravity\022\013\n\003uid\030\001 \001(\r\022\022\n\nani_isJump"
  "\030\002 \001(\010\022\024\n\014ani_isGround\030\003 \001(\010\022\026\n\016ani_isFr"
  "eeFall\030\004 \001(\010\"\207\001\n\rLoginResponse\022\016\n\006result"
  "\030\001 \001(\010\0221\n\010selfdata\030\002 \001(\0132\037.yy.app.protoc"
  "ol.PlayerBaseData\0223\n\nothersdata\030\003 \003(\0132\037."
  "yy.app.protocol.PlayerBaseDatab\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_player_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_player_2eproto_sccs[5] = {
  &scc_info_LoginResponse_player_2eproto.base,
  &scc_info_PlayerBaseData_player_2eproto.base,
  &scc_info_PlayerID_player_2eproto.base,
  &scc_info_PlayerJumpAndGravity_player_2eproto.base,
  &scc_info_PlayerMove_player_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_player_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_player_2eproto = {
  false, false, descriptor_table_protodef_player_2eproto, "player.proto", 678,
  &descriptor_table_player_2eproto_once, descriptor_table_player_2eproto_sccs, descriptor_table_player_2eproto_deps, 5, 0,
  schemas, file_default_instances, TableStruct_player_2eproto::offsets,
  file_level_metadata_player_2eproto, 5, file_level_enum_descriptors_player_2eproto, file_level_service_descriptors_player_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_player_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_player_2eproto)), true);
namespace yy {
namespace app {
namespace protocol {

// ===================================================================

void PlayerID::InitAsDefaultInstance() {
}
class PlayerID::_Internal {
 public:
};

PlayerID::PlayerID(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:yy.app.protocol.PlayerID)
}
PlayerID::PlayerID(const PlayerID& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  uid_ = from.uid_;
  // @@protoc_insertion_point(copy_constructor:yy.app.protocol.PlayerID)
}

void PlayerID::SharedCtor() {
  uid_ = 0u;
}

PlayerID::~PlayerID() {
  // @@protoc_insertion_point(destructor:yy.app.protocol.PlayerID)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void PlayerID::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void PlayerID::ArenaDtor(void* object) {
  PlayerID* _this = reinterpret_cast< PlayerID* >(object);
  (void)_this;
}
void PlayerID::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void PlayerID::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PlayerID& PlayerID::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_PlayerID_player_2eproto.base);
  return *internal_default_instance();
}


void PlayerID::Clear() {
// @@protoc_insertion_point(message_clear_start:yy.app.protocol.PlayerID)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  uid_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PlayerID::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 uid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          uid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PlayerID::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yy.app.protocol.PlayerID)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 uid = 1;
  if (this->uid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_uid(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yy.app.protocol.PlayerID)
  return target;
}

size_t PlayerID::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yy.app.protocol.PlayerID)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 uid = 1;
  if (this->uid() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_uid());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PlayerID::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:yy.app.protocol.PlayerID)
  GOOGLE_DCHECK_NE(&from, this);
  const PlayerID* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<PlayerID>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:yy.app.protocol.PlayerID)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:yy.app.protocol.PlayerID)
    MergeFrom(*source);
  }
}

void PlayerID::MergeFrom(const PlayerID& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yy.app.protocol.PlayerID)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.uid() != 0) {
    _internal_set_uid(from._internal_uid());
  }
}

void PlayerID::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:yy.app.protocol.PlayerID)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PlayerID::CopyFrom(const PlayerID& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yy.app.protocol.PlayerID)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerID::IsInitialized() const {
  return true;
}

void PlayerID::InternalSwap(PlayerID* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(uid_, other->uid_);
}

::PROTOBUF_NAMESPACE_ID::Metadata PlayerID::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void PlayerBaseData::InitAsDefaultInstance() {
}
class PlayerBaseData::_Internal {
 public:
};

PlayerBaseData::PlayerBaseData(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:yy.app.protocol.PlayerBaseData)
}
PlayerBaseData::PlayerBaseData(const PlayerBaseData& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  position_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_position().empty()) {
    position_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_position(),
      GetArena());
  }
  rotation_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_rotation().empty()) {
    rotation_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_rotation(),
      GetArena());
  }
  ::memcpy(&uid_, &from.uid_,
    static_cast<size_t>(reinterpret_cast<char*>(&ani_motionspeed_) -
    reinterpret_cast<char*>(&uid_)) + sizeof(ani_motionspeed_));
  // @@protoc_insertion_point(copy_constructor:yy.app.protocol.PlayerBaseData)
}

void PlayerBaseData::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_PlayerBaseData_player_2eproto.base);
  position_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  rotation_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&uid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ani_motionspeed_) -
      reinterpret_cast<char*>(&uid_)) + sizeof(ani_motionspeed_));
}

PlayerBaseData::~PlayerBaseData() {
  // @@protoc_insertion_point(destructor:yy.app.protocol.PlayerBaseData)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void PlayerBaseData::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  position_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  rotation_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void PlayerBaseData::ArenaDtor(void* object) {
  PlayerBaseData* _this = reinterpret_cast< PlayerBaseData* >(object);
  (void)_this;
}
void PlayerBaseData::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void PlayerBaseData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PlayerBaseData& PlayerBaseData::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_PlayerBaseData_player_2eproto.base);
  return *internal_default_instance();
}


void PlayerBaseData::Clear() {
// @@protoc_insertion_point(message_clear_start:yy.app.protocol.PlayerBaseData)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  position_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  rotation_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&uid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ani_motionspeed_) -
      reinterpret_cast<char*>(&uid_)) + sizeof(ani_motionspeed_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PlayerBaseData::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 uid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          uid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 sockfd = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          sockfd_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 state = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          state_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 hp_current = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          hp_current_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 hp_max = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          hp_max_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes position = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          auto str = _internal_mutable_position();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes rotation = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 58)) {
          auto str = _internal_mutable_rotation();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // float ani_speed = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 69)) {
          ani_speed_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // bool ani_isJump = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 72)) {
          ani_isjump_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool ani_isGround = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 80)) {
          ani_isground_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool ani_isFreeFall = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 88)) {
          ani_isfreefall_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // float ani_motionSpeed = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 101)) {
          ani_motionspeed_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PlayerBaseData::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yy.app.protocol.PlayerBaseData)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 uid = 1;
  if (this->uid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_uid(), target);
  }

  // int32 sockfd = 2;
  if (this->sockfd() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_sockfd(), target);
  }

  // int32 state = 3;
  if (this->state() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_state(), target);
  }

  // int32 hp_current = 4;
  if (this->hp_current() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(4, this->_internal_hp_current(), target);
  }

  // int32 hp_max = 5;
  if (this->hp_max() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(5, this->_internal_hp_max(), target);
  }

  // bytes position = 6;
  if (this->position().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        6, this->_internal_position(), target);
  }

  // bytes rotation = 7;
  if (this->rotation().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        7, this->_internal_rotation(), target);
  }

  // float ani_speed = 8;
  if (!(this->ani_speed() <= 0 && this->ani_speed() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(8, this->_internal_ani_speed(), target);
  }

  // bool ani_isJump = 9;
  if (this->ani_isjump() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(9, this->_internal_ani_isjump(), target);
  }

  // bool ani_isGround = 10;
  if (this->ani_isground() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(10, this->_internal_ani_isground(), target);
  }

  // bool ani_isFreeFall = 11;
  if (this->ani_isfreefall() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(11, this->_internal_ani_isfreefall(), target);
  }

  // float ani_motionSpeed = 12;
  if (!(this->ani_motionspeed() <= 0 && this->ani_motionspeed() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(12, this->_internal_ani_motionspeed(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yy.app.protocol.PlayerBaseData)
  return target;
}

size_t PlayerBaseData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yy.app.protocol.PlayerBaseData)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes position = 6;
  if (this->position().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_position());
  }

  // bytes rotation = 7;
  if (this->rotation().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_rotation());
  }

  // uint32 uid = 1;
  if (this->uid() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_uid());
  }

  // int32 sockfd = 2;
  if (this->sockfd() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_sockfd());
  }

  // int32 state = 3;
  if (this->state() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_state());
  }

  // int32 hp_current = 4;
  if (this->hp_current() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_hp_current());
  }

  // int32 hp_max = 5;
  if (this->hp_max() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_hp_max());
  }

  // float ani_speed = 8;
  if (!(this->ani_speed() <= 0 && this->ani_speed() >= 0)) {
    total_size += 1 + 4;
  }

  // bool ani_isJump = 9;
  if (this->ani_isjump() != 0) {
    total_size += 1 + 1;
  }

  // bool ani_isGround = 10;
  if (this->ani_isground() != 0) {
    total_size += 1 + 1;
  }

  // bool ani_isFreeFall = 11;
  if (this->ani_isfreefall() != 0) {
    total_size += 1 + 1;
  }

  // float ani_motionSpeed = 12;
  if (!(this->ani_motionspeed() <= 0 && this->ani_motionspeed() >= 0)) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PlayerBaseData::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:yy.app.protocol.PlayerBaseData)
  GOOGLE_DCHECK_NE(&from, this);
  const PlayerBaseData* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<PlayerBaseData>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:yy.app.protocol.PlayerBaseData)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:yy.app.protocol.PlayerBaseData)
    MergeFrom(*source);
  }
}

void PlayerBaseData::MergeFrom(const PlayerBaseData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yy.app.protocol.PlayerBaseData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.position().size() > 0) {
    _internal_set_position(from._internal_position());
  }
  if (from.rotation().size() > 0) {
    _internal_set_rotation(from._internal_rotation());
  }
  if (from.uid() != 0) {
    _internal_set_uid(from._internal_uid());
  }
  if (from.sockfd() != 0) {
    _internal_set_sockfd(from._internal_sockfd());
  }
  if (from.state() != 0) {
    _internal_set_state(from._internal_state());
  }
  if (from.hp_current() != 0) {
    _internal_set_hp_current(from._internal_hp_current());
  }
  if (from.hp_max() != 0) {
    _internal_set_hp_max(from._internal_hp_max());
  }
  if (!(from.ani_speed() <= 0 && from.ani_speed() >= 0)) {
    _internal_set_ani_speed(from._internal_ani_speed());
  }
  if (from.ani_isjump() != 0) {
    _internal_set_ani_isjump(from._internal_ani_isjump());
  }
  if (from.ani_isground() != 0) {
    _internal_set_ani_isground(from._internal_ani_isground());
  }
  if (from.ani_isfreefall() != 0) {
    _internal_set_ani_isfreefall(from._internal_ani_isfreefall());
  }
  if (!(from.ani_motionspeed() <= 0 && from.ani_motionspeed() >= 0)) {
    _internal_set_ani_motionspeed(from._internal_ani_motionspeed());
  }
}

void PlayerBaseData::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:yy.app.protocol.PlayerBaseData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PlayerBaseData::CopyFrom(const PlayerBaseData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yy.app.protocol.PlayerBaseData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerBaseData::IsInitialized() const {
  return true;
}

void PlayerBaseData::InternalSwap(PlayerBaseData* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  position_.Swap(&other->position_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  rotation_.Swap(&other->rotation_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PlayerBaseData, ani_motionspeed_)
      + sizeof(PlayerBaseData::ani_motionspeed_)
      - PROTOBUF_FIELD_OFFSET(PlayerBaseData, uid_)>(
          reinterpret_cast<char*>(&uid_),
          reinterpret_cast<char*>(&other->uid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PlayerBaseData::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void PlayerMove::InitAsDefaultInstance() {
}
class PlayerMove::_Internal {
 public:
};

PlayerMove::PlayerMove(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:yy.app.protocol.PlayerMove)
}
PlayerMove::PlayerMove(const PlayerMove& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  position_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_position().empty()) {
    position_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_position(),
      GetArena());
  }
  rotation_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_rotation().empty()) {
    rotation_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_rotation(),
      GetArena());
  }
  move_target_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_move_target().empty()) {
    move_target_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_move_target(),
      GetArena());
  }
  ::memcpy(&uid_, &from.uid_,
    static_cast<size_t>(reinterpret_cast<char*>(&ani_motionspeed_) -
    reinterpret_cast<char*>(&uid_)) + sizeof(ani_motionspeed_));
  // @@protoc_insertion_point(copy_constructor:yy.app.protocol.PlayerMove)
}

void PlayerMove::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_PlayerMove_player_2eproto.base);
  position_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  rotation_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  move_target_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&uid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ani_motionspeed_) -
      reinterpret_cast<char*>(&uid_)) + sizeof(ani_motionspeed_));
}

PlayerMove::~PlayerMove() {
  // @@protoc_insertion_point(destructor:yy.app.protocol.PlayerMove)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void PlayerMove::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  position_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  rotation_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  move_target_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void PlayerMove::ArenaDtor(void* object) {
  PlayerMove* _this = reinterpret_cast< PlayerMove* >(object);
  (void)_this;
}
void PlayerMove::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void PlayerMove::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PlayerMove& PlayerMove::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_PlayerMove_player_2eproto.base);
  return *internal_default_instance();
}


void PlayerMove::Clear() {
// @@protoc_insertion_point(message_clear_start:yy.app.protocol.PlayerMove)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  position_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  rotation_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  move_target_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&uid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ani_motionspeed_) -
      reinterpret_cast<char*>(&uid_)) + sizeof(ani_motionspeed_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PlayerMove::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 uid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          uid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes position = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_position();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes rotation = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_rotation();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bytes move_target = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_move_target();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // float ani_speed = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 45)) {
          ani_speed_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // float ani_motionSpeed = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 53)) {
          ani_motionspeed_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PlayerMove::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yy.app.protocol.PlayerMove)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 uid = 1;
  if (this->uid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_uid(), target);
  }

  // bytes position = 2;
  if (this->position().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_position(), target);
  }

  // bytes rotation = 3;
  if (this->rotation().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_rotation(), target);
  }

  // bytes move_target = 4;
  if (this->move_target().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        4, this->_internal_move_target(), target);
  }

  // float ani_speed = 5;
  if (!(this->ani_speed() <= 0 && this->ani_speed() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(5, this->_internal_ani_speed(), target);
  }

  // float ani_motionSpeed = 6;
  if (!(this->ani_motionspeed() <= 0 && this->ani_motionspeed() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(6, this->_internal_ani_motionspeed(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yy.app.protocol.PlayerMove)
  return target;
}

size_t PlayerMove::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yy.app.protocol.PlayerMove)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes position = 2;
  if (this->position().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_position());
  }

  // bytes rotation = 3;
  if (this->rotation().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_rotation());
  }

  // bytes move_target = 4;
  if (this->move_target().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_move_target());
  }

  // uint32 uid = 1;
  if (this->uid() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_uid());
  }

  // float ani_speed = 5;
  if (!(this->ani_speed() <= 0 && this->ani_speed() >= 0)) {
    total_size += 1 + 4;
  }

  // float ani_motionSpeed = 6;
  if (!(this->ani_motionspeed() <= 0 && this->ani_motionspeed() >= 0)) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PlayerMove::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:yy.app.protocol.PlayerMove)
  GOOGLE_DCHECK_NE(&from, this);
  const PlayerMove* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<PlayerMove>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:yy.app.protocol.PlayerMove)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:yy.app.protocol.PlayerMove)
    MergeFrom(*source);
  }
}

void PlayerMove::MergeFrom(const PlayerMove& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yy.app.protocol.PlayerMove)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.position().size() > 0) {
    _internal_set_position(from._internal_position());
  }
  if (from.rotation().size() > 0) {
    _internal_set_rotation(from._internal_rotation());
  }
  if (from.move_target().size() > 0) {
    _internal_set_move_target(from._internal_move_target());
  }
  if (from.uid() != 0) {
    _internal_set_uid(from._internal_uid());
  }
  if (!(from.ani_speed() <= 0 && from.ani_speed() >= 0)) {
    _internal_set_ani_speed(from._internal_ani_speed());
  }
  if (!(from.ani_motionspeed() <= 0 && from.ani_motionspeed() >= 0)) {
    _internal_set_ani_motionspeed(from._internal_ani_motionspeed());
  }
}

void PlayerMove::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:yy.app.protocol.PlayerMove)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PlayerMove::CopyFrom(const PlayerMove& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yy.app.protocol.PlayerMove)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerMove::IsInitialized() const {
  return true;
}

void PlayerMove::InternalSwap(PlayerMove* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  position_.Swap(&other->position_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  rotation_.Swap(&other->rotation_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  move_target_.Swap(&other->move_target_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PlayerMove, ani_motionspeed_)
      + sizeof(PlayerMove::ani_motionspeed_)
      - PROTOBUF_FIELD_OFFSET(PlayerMove, uid_)>(
          reinterpret_cast<char*>(&uid_),
          reinterpret_cast<char*>(&other->uid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PlayerMove::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void PlayerJumpAndGravity::InitAsDefaultInstance() {
}
class PlayerJumpAndGravity::_Internal {
 public:
};

PlayerJumpAndGravity::PlayerJumpAndGravity(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:yy.app.protocol.PlayerJumpAndGravity)
}
PlayerJumpAndGravity::PlayerJumpAndGravity(const PlayerJumpAndGravity& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&uid_, &from.uid_,
    static_cast<size_t>(reinterpret_cast<char*>(&ani_isfreefall_) -
    reinterpret_cast<char*>(&uid_)) + sizeof(ani_isfreefall_));
  // @@protoc_insertion_point(copy_constructor:yy.app.protocol.PlayerJumpAndGravity)
}

void PlayerJumpAndGravity::SharedCtor() {
  ::memset(&uid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ani_isfreefall_) -
      reinterpret_cast<char*>(&uid_)) + sizeof(ani_isfreefall_));
}

PlayerJumpAndGravity::~PlayerJumpAndGravity() {
  // @@protoc_insertion_point(destructor:yy.app.protocol.PlayerJumpAndGravity)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void PlayerJumpAndGravity::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void PlayerJumpAndGravity::ArenaDtor(void* object) {
  PlayerJumpAndGravity* _this = reinterpret_cast< PlayerJumpAndGravity* >(object);
  (void)_this;
}
void PlayerJumpAndGravity::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void PlayerJumpAndGravity::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PlayerJumpAndGravity& PlayerJumpAndGravity::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_PlayerJumpAndGravity_player_2eproto.base);
  return *internal_default_instance();
}


void PlayerJumpAndGravity::Clear() {
// @@protoc_insertion_point(message_clear_start:yy.app.protocol.PlayerJumpAndGravity)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&uid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ani_isfreefall_) -
      reinterpret_cast<char*>(&uid_)) + sizeof(ani_isfreefall_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PlayerJumpAndGravity::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 uid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          uid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool ani_isJump = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          ani_isjump_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool ani_isGround = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          ani_isground_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool ani_isFreeFall = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          ani_isfreefall_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PlayerJumpAndGravity::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yy.app.protocol.PlayerJumpAndGravity)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 uid = 1;
  if (this->uid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_uid(), target);
  }

  // bool ani_isJump = 2;
  if (this->ani_isjump() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(2, this->_internal_ani_isjump(), target);
  }

  // bool ani_isGround = 3;
  if (this->ani_isground() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(3, this->_internal_ani_isground(), target);
  }

  // bool ani_isFreeFall = 4;
  if (this->ani_isfreefall() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(4, this->_internal_ani_isfreefall(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yy.app.protocol.PlayerJumpAndGravity)
  return target;
}

size_t PlayerJumpAndGravity::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yy.app.protocol.PlayerJumpAndGravity)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 uid = 1;
  if (this->uid() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_uid());
  }

  // bool ani_isJump = 2;
  if (this->ani_isjump() != 0) {
    total_size += 1 + 1;
  }

  // bool ani_isGround = 3;
  if (this->ani_isground() != 0) {
    total_size += 1 + 1;
  }

  // bool ani_isFreeFall = 4;
  if (this->ani_isfreefall() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PlayerJumpAndGravity::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:yy.app.protocol.PlayerJumpAndGravity)
  GOOGLE_DCHECK_NE(&from, this);
  const PlayerJumpAndGravity* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<PlayerJumpAndGravity>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:yy.app.protocol.PlayerJumpAndGravity)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:yy.app.protocol.PlayerJumpAndGravity)
    MergeFrom(*source);
  }
}

void PlayerJumpAndGravity::MergeFrom(const PlayerJumpAndGravity& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yy.app.protocol.PlayerJumpAndGravity)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.uid() != 0) {
    _internal_set_uid(from._internal_uid());
  }
  if (from.ani_isjump() != 0) {
    _internal_set_ani_isjump(from._internal_ani_isjump());
  }
  if (from.ani_isground() != 0) {
    _internal_set_ani_isground(from._internal_ani_isground());
  }
  if (from.ani_isfreefall() != 0) {
    _internal_set_ani_isfreefall(from._internal_ani_isfreefall());
  }
}

void PlayerJumpAndGravity::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:yy.app.protocol.PlayerJumpAndGravity)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PlayerJumpAndGravity::CopyFrom(const PlayerJumpAndGravity& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yy.app.protocol.PlayerJumpAndGravity)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PlayerJumpAndGravity::IsInitialized() const {
  return true;
}

void PlayerJumpAndGravity::InternalSwap(PlayerJumpAndGravity* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PlayerJumpAndGravity, ani_isfreefall_)
      + sizeof(PlayerJumpAndGravity::ani_isfreefall_)
      - PROTOBUF_FIELD_OFFSET(PlayerJumpAndGravity, uid_)>(
          reinterpret_cast<char*>(&uid_),
          reinterpret_cast<char*>(&other->uid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PlayerJumpAndGravity::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void LoginResponse::InitAsDefaultInstance() {
  ::yy::app::protocol::_LoginResponse_default_instance_._instance.get_mutable()->selfdata_ = const_cast< ::yy::app::protocol::PlayerBaseData*>(
      ::yy::app::protocol::PlayerBaseData::internal_default_instance());
}
class LoginResponse::_Internal {
 public:
  static const ::yy::app::protocol::PlayerBaseData& selfdata(const LoginResponse* msg);
};

const ::yy::app::protocol::PlayerBaseData&
LoginResponse::_Internal::selfdata(const LoginResponse* msg) {
  return *msg->selfdata_;
}
LoginResponse::LoginResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  othersdata_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:yy.app.protocol.LoginResponse)
}
LoginResponse::LoginResponse(const LoginResponse& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      othersdata_(from.othersdata_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_selfdata()) {
    selfdata_ = new ::yy::app::protocol::PlayerBaseData(*from.selfdata_);
  } else {
    selfdata_ = nullptr;
  }
  result_ = from.result_;
  // @@protoc_insertion_point(copy_constructor:yy.app.protocol.LoginResponse)
}

void LoginResponse::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_LoginResponse_player_2eproto.base);
  ::memset(&selfdata_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&result_) -
      reinterpret_cast<char*>(&selfdata_)) + sizeof(result_));
}

LoginResponse::~LoginResponse() {
  // @@protoc_insertion_point(destructor:yy.app.protocol.LoginResponse)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void LoginResponse::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete selfdata_;
}

void LoginResponse::ArenaDtor(void* object) {
  LoginResponse* _this = reinterpret_cast< LoginResponse* >(object);
  (void)_this;
}
void LoginResponse::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void LoginResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const LoginResponse& LoginResponse::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_LoginResponse_player_2eproto.base);
  return *internal_default_instance();
}


void LoginResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:yy.app.protocol.LoginResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  othersdata_.Clear();
  if (GetArena() == nullptr && selfdata_ != nullptr) {
    delete selfdata_;
  }
  selfdata_ = nullptr;
  result_ = false;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* LoginResponse::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bool result = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          result_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .yy.app.protocol.PlayerBaseData selfdata = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_selfdata(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated .yy.app.protocol.PlayerBaseData othersdata = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_othersdata(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* LoginResponse::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yy.app.protocol.LoginResponse)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bool result = 1;
  if (this->result() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(1, this->_internal_result(), target);
  }

  // .yy.app.protocol.PlayerBaseData selfdata = 2;
  if (this->has_selfdata()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::selfdata(this), target, stream);
  }

  // repeated .yy.app.protocol.PlayerBaseData othersdata = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_othersdata_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, this->_internal_othersdata(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yy.app.protocol.LoginResponse)
  return target;
}

size_t LoginResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yy.app.protocol.LoginResponse)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .yy.app.protocol.PlayerBaseData othersdata = 3;
  total_size += 1UL * this->_internal_othersdata_size();
  for (const auto& msg : this->othersdata_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // .yy.app.protocol.PlayerBaseData selfdata = 2;
  if (this->has_selfdata()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *selfdata_);
  }

  // bool result = 1;
  if (this->result() != 0) {
    total_size += 1 + 1;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LoginResponse::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:yy.app.protocol.LoginResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const LoginResponse* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<LoginResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:yy.app.protocol.LoginResponse)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:yy.app.protocol.LoginResponse)
    MergeFrom(*source);
  }
}

void LoginResponse::MergeFrom(const LoginResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yy.app.protocol.LoginResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  othersdata_.MergeFrom(from.othersdata_);
  if (from.has_selfdata()) {
    _internal_mutable_selfdata()->::yy::app::protocol::PlayerBaseData::MergeFrom(from._internal_selfdata());
  }
  if (from.result() != 0) {
    _internal_set_result(from._internal_result());
  }
}

void LoginResponse::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:yy.app.protocol.LoginResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LoginResponse::CopyFrom(const LoginResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yy.app.protocol.LoginResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LoginResponse::IsInitialized() const {
  return true;
}

void LoginResponse::InternalSwap(LoginResponse* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  othersdata_.InternalSwap(&other->othersdata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LoginResponse, result_)
      + sizeof(LoginResponse::result_)
      - PROTOBUF_FIELD_OFFSET(LoginResponse, selfdata_)>(
          reinterpret_cast<char*>(&selfdata_),
          reinterpret_cast<char*>(&other->selfdata_));
}

::PROTOBUF_NAMESPACE_ID::Metadata LoginResponse::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protocol
}  // namespace app
}  // namespace yy
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::yy::app::protocol::PlayerID* Arena::CreateMaybeMessage< ::yy::app::protocol::PlayerID >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yy::app::protocol::PlayerID >(arena);
}
template<> PROTOBUF_NOINLINE ::yy::app::protocol::PlayerBaseData* Arena::CreateMaybeMessage< ::yy::app::protocol::PlayerBaseData >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yy::app::protocol::PlayerBaseData >(arena);
}
template<> PROTOBUF_NOINLINE ::yy::app::protocol::PlayerMove* Arena::CreateMaybeMessage< ::yy::app::protocol::PlayerMove >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yy::app::protocol::PlayerMove >(arena);
}
template<> PROTOBUF_NOINLINE ::yy::app::protocol::PlayerJumpAndGravity* Arena::CreateMaybeMessage< ::yy::app::protocol::PlayerJumpAndGravity >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yy::app::protocol::PlayerJumpAndGravity >(arena);
}
template<> PROTOBUF_NOINLINE ::yy::app::protocol::LoginResponse* Arena::CreateMaybeMessage< ::yy::app::protocol::LoginResponse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yy::app::protocol::LoginResponse >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
