syntax = "proto3";
package yy.protocol.app;



message PlayerBaseData
{
    uint32     uid         = 1;
    bytes      conn_name   = 2;
    int32      state       = 3;
    int32      hp_current  = 4;
    int32      hp_max      = 5;
    PlayerMove movement    = 6;
    PlayerJumpAndGravity jump_and_gravity = 7;
}
message PlayerMove
{
    bytes       position = 2;
    bytes       rotation = 3;
    float       ani_speed = 5;
    float       ani_motion_speed = 6;

    bytes       move_target = 4;
}
message PlayerJumpAndGravity
{
    bool     ani_is_jump = 2;
    bool     ani_is_ground = 3;
    bool     ani_is_freefall = 4;
}

//! 客户端发送和接收
message PlayerLeave
{
    uint32   leaver_uid = 1;
};


//! 客户端发送自己的移动数据，服务端验证，然后返回让客户端接收
message SelfMovement
{
    uint32      uid = 1;
    PlayerMove movement = 2;
}
//! 客户端接收其它玩家的移动
message OtherMovement
{
    uint32      uid = 1;
    PlayerMove  movement = 2;
}


//! 客户端发送自己的跳跃数据，服务端验证，然后返回让客户端接收
message SelfJumpAndGravity
{
    uint32      uid = 1;
    PlayerJumpAndGravity jump_and_gravity = 2;
}
//! 客户端接收其它玩家的跳跃
message OtherJumpAndGravity
{
    uint32      uid = 1;
    PlayerJumpAndGravity jump_and_gravity = 2;
}


//! 客户端的登录请求
message LoginRequest
{
    bytes  conn_name   = 1;
}
//! 服务器端返回给客户端的登录结果
message LoginResponse
{
    bool result = 1;
    PlayerBaseData self_data = 2;
    repeated PlayerBaseData other_datas = 3;
}


//! 如果收到其它玩家的移动或跳跃数据，但是没有该玩家的基础数据，则先请求之
message OtherPlayerDataRequest
{
    uint32     requester_uid        = 1;
    uint32     requested_uid        = 2;
}

//! 如果收到其它玩家的移动或跳跃数据，但是没有该玩家的基础数据，则先请求之
message OtherPlayerDataResponse
{
    PlayerBaseData other_data = 1;
}

