// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: query.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_query_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_query_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023000 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_query_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_query_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_query_2eproto;
namespace yy {
namespace protobuf {
class Answer;
struct AnswerDefaultTypeInternal;
extern AnswerDefaultTypeInternal _Answer_default_instance_;
class Empty;
struct EmptyDefaultTypeInternal;
extern EmptyDefaultTypeInternal _Empty_default_instance_;
class Query;
struct QueryDefaultTypeInternal;
extern QueryDefaultTypeInternal _Query_default_instance_;
}  // namespace protobuf
}  // namespace yy
PROTOBUF_NAMESPACE_OPEN
template <>
::yy::protobuf::Answer* Arena::CreateMaybeMessage<::yy::protobuf::Answer>(Arena*);
template <>
::yy::protobuf::Empty* Arena::CreateMaybeMessage<::yy::protobuf::Empty>(Arena*);
template <>
::yy::protobuf::Query* Arena::CreateMaybeMessage<::yy::protobuf::Query>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace yy {
namespace protobuf {

// ===================================================================


// -------------------------------------------------------------------

class Query final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yy.protobuf.Query) */ {
 public:
  inline Query() : Query(nullptr) {}
  ~Query() override;
  explicit PROTOBUF_CONSTEXPR Query(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Query(const Query& from);
  Query(Query&& from) noexcept
    : Query() {
    *this = ::std::move(from);
  }

  inline Query& operator=(const Query& from) {
    CopyFrom(from);
    return *this;
  }
  inline Query& operator=(Query&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Query& default_instance() {
    return *internal_default_instance();
  }
  static inline const Query* internal_default_instance() {
    return reinterpret_cast<const Query*>(
               &_Query_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Query& a, Query& b) {
    a.Swap(&b);
  }
  inline void Swap(Query* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Query* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Query* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Query>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Query& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Query& from) {
    Query::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Query* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "yy.protobuf.Query";
  }
  protected:
  explicit Query(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kQuestionFieldNumber = 3,
    kQuestionerFieldNumber = 2,
    kIdFieldNumber = 1,
  };
  // repeated string question = 3;
  int question_size() const;
  private:
  int _internal_question_size() const;

  public:
  void clear_question() ;
  const std::string& question(int index) const;
  std::string* mutable_question(int index);
  void set_question(int index, const std::string& value);
  void set_question(int index, std::string&& value);
  void set_question(int index, const char* value);
  void set_question(int index, const char* value, std::size_t size);
  void set_question(int index, absl::string_view value);
  std::string* add_question();
  void add_question(const std::string& value);
  void add_question(std::string&& value);
  void add_question(const char* value);
  void add_question(const char* value, std::size_t size);
  void add_question(absl::string_view value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& question() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_question();

  private:
  const std::string& _internal_question(int index) const;
  std::string* _internal_add_question();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& _internal_question() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* _internal_mutable_question();

  public:
  // required string questioner = 2;
  bool has_questioner() const;
  void clear_questioner() ;
  const std::string& questioner() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_questioner(Arg_&& arg, Args_... args);
  std::string* mutable_questioner();
  PROTOBUF_NODISCARD std::string* release_questioner();
  void set_allocated_questioner(std::string* ptr);

  private:
  const std::string& _internal_questioner() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_questioner(
      const std::string& value);
  std::string* _internal_mutable_questioner();

  public:
  // required int64 id = 1;
  bool has_id() const;
  void clear_id() ;
  ::int64_t id() const;
  void set_id(::int64_t value);

  private:
  ::int64_t _internal_id() const;
  void _internal_set_id(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:yy.protobuf.Query)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  ::size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> question_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr questioner_;
    ::int64_t id_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_query_2eproto;
};// -------------------------------------------------------------------

class Answer final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yy.protobuf.Answer) */ {
 public:
  inline Answer() : Answer(nullptr) {}
  ~Answer() override;
  explicit PROTOBUF_CONSTEXPR Answer(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Answer(const Answer& from);
  Answer(Answer&& from) noexcept
    : Answer() {
    *this = ::std::move(from);
  }

  inline Answer& operator=(const Answer& from) {
    CopyFrom(from);
    return *this;
  }
  inline Answer& operator=(Answer&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Answer& default_instance() {
    return *internal_default_instance();
  }
  static inline const Answer* internal_default_instance() {
    return reinterpret_cast<const Answer*>(
               &_Answer_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Answer& a, Answer& b) {
    a.Swap(&b);
  }
  inline void Swap(Answer* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Answer* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Answer* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Answer>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Answer& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Answer& from) {
    Answer::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Answer* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "yy.protobuf.Answer";
  }
  protected:
  explicit Answer(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSolutionFieldNumber = 4,
    kQuestionerFieldNumber = 2,
    kAnswererFieldNumber = 3,
    kIdFieldNumber = 1,
  };
  // repeated string solution = 4;
  int solution_size() const;
  private:
  int _internal_solution_size() const;

  public:
  void clear_solution() ;
  const std::string& solution(int index) const;
  std::string* mutable_solution(int index);
  void set_solution(int index, const std::string& value);
  void set_solution(int index, std::string&& value);
  void set_solution(int index, const char* value);
  void set_solution(int index, const char* value, std::size_t size);
  void set_solution(int index, absl::string_view value);
  std::string* add_solution();
  void add_solution(const std::string& value);
  void add_solution(std::string&& value);
  void add_solution(const char* value);
  void add_solution(const char* value, std::size_t size);
  void add_solution(absl::string_view value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& solution() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_solution();

  private:
  const std::string& _internal_solution(int index) const;
  std::string* _internal_add_solution();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& _internal_solution() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* _internal_mutable_solution();

  public:
  // required string questioner = 2;
  bool has_questioner() const;
  void clear_questioner() ;
  const std::string& questioner() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_questioner(Arg_&& arg, Args_... args);
  std::string* mutable_questioner();
  PROTOBUF_NODISCARD std::string* release_questioner();
  void set_allocated_questioner(std::string* ptr);

  private:
  const std::string& _internal_questioner() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_questioner(
      const std::string& value);
  std::string* _internal_mutable_questioner();

  public:
  // required string answerer = 3;
  bool has_answerer() const;
  void clear_answerer() ;
  const std::string& answerer() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_answerer(Arg_&& arg, Args_... args);
  std::string* mutable_answerer();
  PROTOBUF_NODISCARD std::string* release_answerer();
  void set_allocated_answerer(std::string* ptr);

  private:
  const std::string& _internal_answerer() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_answerer(
      const std::string& value);
  std::string* _internal_mutable_answerer();

  public:
  // required int64 id = 1;
  bool has_id() const;
  void clear_id() ;
  ::int64_t id() const;
  void set_id(::int64_t value);

  private:
  ::int64_t _internal_id() const;
  void _internal_set_id(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:yy.protobuf.Answer)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  ::size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> solution_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr questioner_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr answerer_;
    ::int64_t id_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_query_2eproto;
};// -------------------------------------------------------------------

class Empty final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:yy.protobuf.Empty) */ {
 public:
  inline Empty() : Empty(nullptr) {}
  ~Empty() override;
  explicit PROTOBUF_CONSTEXPR Empty(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Empty(const Empty& from);
  Empty(Empty&& from) noexcept
    : Empty() {
    *this = ::std::move(from);
  }

  inline Empty& operator=(const Empty& from) {
    CopyFrom(from);
    return *this;
  }
  inline Empty& operator=(Empty&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Empty& default_instance() {
    return *internal_default_instance();
  }
  static inline const Empty* internal_default_instance() {
    return reinterpret_cast<const Empty*>(
               &_Empty_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Empty& a, Empty& b) {
    a.Swap(&b);
  }
  inline void Swap(Empty* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Empty* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Empty* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Empty>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Empty& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Empty& from) {
    Empty::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Empty* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "yy.protobuf.Empty";
  }
  protected:
  explicit Empty(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
  };
  // optional int32 id = 1;
  bool has_id() const;
  void clear_id() ;
  ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:yy.protobuf.Empty)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::int32_t id_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_query_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Query

// required int64 id = 1;
inline bool Query::has_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Query::clear_id() {
  _impl_.id_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline ::int64_t Query::id() const {
  // @@protoc_insertion_point(field_get:yy.protobuf.Query.id)
  return _internal_id();
}
inline void Query::set_id(::int64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:yy.protobuf.Query.id)
}
inline ::int64_t Query::_internal_id() const {
  return _impl_.id_;
}
inline void Query::_internal_set_id(::int64_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.id_ = value;
}

// required string questioner = 2;
inline bool Query::has_questioner() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Query::clear_questioner() {
  _impl_.questioner_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Query::questioner() const {
  // @@protoc_insertion_point(field_get:yy.protobuf.Query.questioner)
  return _internal_questioner();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Query::set_questioner(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.questioner_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:yy.protobuf.Query.questioner)
}
inline std::string* Query::mutable_questioner() {
  std::string* _s = _internal_mutable_questioner();
  // @@protoc_insertion_point(field_mutable:yy.protobuf.Query.questioner)
  return _s;
}
inline const std::string& Query::_internal_questioner() const {
  return _impl_.questioner_.Get();
}
inline void Query::_internal_set_questioner(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;


  _impl_.questioner_.Set(value, GetArenaForAllocation());
}
inline std::string* Query::_internal_mutable_questioner() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.questioner_.Mutable( GetArenaForAllocation());
}
inline std::string* Query::release_questioner() {
  // @@protoc_insertion_point(field_release:yy.protobuf.Query.questioner)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.questioner_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.questioner_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Query::set_allocated_questioner(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.questioner_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.questioner_.IsDefault()) {
          _impl_.questioner_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:yy.protobuf.Query.questioner)
}

// repeated string question = 3;
inline int Query::_internal_question_size() const {
  return _impl_.question_.size();
}
inline int Query::question_size() const {
  return _internal_question_size();
}
inline void Query::clear_question() {
  _internal_mutable_question()->Clear();
}
inline std::string* Query::add_question() {
  std::string* _s = _internal_add_question();
  // @@protoc_insertion_point(field_add_mutable:yy.protobuf.Query.question)
  return _s;
}
inline const std::string& Query::question(int index) const {
  // @@protoc_insertion_point(field_get:yy.protobuf.Query.question)
  return _internal_question(index);
}
inline std::string* Query::mutable_question(int index) {
  // @@protoc_insertion_point(field_mutable:yy.protobuf.Query.question)
  return _internal_mutable_question()->Mutable(index);
}
inline void Query::set_question(int index, const std::string& value) {
  _internal_mutable_question()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:yy.protobuf.Query.question)
}
inline void Query::set_question(int index, std::string&& value) {
  _internal_mutable_question()->Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:yy.protobuf.Query.question)
}
inline void Query::set_question(int index, const char* value) {
  ABSL_DCHECK(value != nullptr);
  _internal_mutable_question()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:yy.protobuf.Query.question)
}
inline void Query::set_question(int index, const char* value,
                              std::size_t size) {
  _internal_mutable_question()->Mutable(index)->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:yy.protobuf.Query.question)
}
inline void Query::set_question(int index, absl::string_view value) {
  _internal_mutable_question()->Mutable(index)->assign(value.data(),
                                                     value.size());
  // @@protoc_insertion_point(field_set_string_piece:yy.protobuf.Query.question)
}
inline void Query::add_question(const std::string& value) {
  _internal_mutable_question()->Add()->assign(value);
  // @@protoc_insertion_point(field_add:yy.protobuf.Query.question)
}
inline void Query::add_question(std::string&& value) {
  _internal_mutable_question()->Add(std::move(value));
  // @@protoc_insertion_point(field_add:yy.protobuf.Query.question)
}
inline void Query::add_question(const char* value) {
  ABSL_DCHECK(value != nullptr);
  _internal_mutable_question()->Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:yy.protobuf.Query.question)
}
inline void Query::add_question(const char* value, std::size_t size) {
  _internal_mutable_question()->Add()->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:yy.protobuf.Query.question)
}
inline void Query::add_question(absl::string_view value) {
  _internal_mutable_question()->Add()->assign(value.data(), value.size());
  // @@protoc_insertion_point(field_add_string_piece:yy.protobuf.Query.question)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Query::question() const {
  // @@protoc_insertion_point(field_list:yy.protobuf.Query.question)
  return _internal_question();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* Query::mutable_question() {
  // @@protoc_insertion_point(field_mutable_list:yy.protobuf.Query.question)
  return _internal_mutable_question();
}
inline const std::string& Query::_internal_question(int index) const {
  return _internal_question().Get(index);
}
inline std::string* Query::_internal_add_question() {
  return _internal_mutable_question()->Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Query::_internal_question() const {
  return _impl_.question_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Query::_internal_mutable_question() {
  return &_impl_.question_;
}

// -------------------------------------------------------------------

// Answer

// required int64 id = 1;
inline bool Answer::has_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void Answer::clear_id() {
  _impl_.id_ = ::int64_t{0};
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline ::int64_t Answer::id() const {
  // @@protoc_insertion_point(field_get:yy.protobuf.Answer.id)
  return _internal_id();
}
inline void Answer::set_id(::int64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:yy.protobuf.Answer.id)
}
inline ::int64_t Answer::_internal_id() const {
  return _impl_.id_;
}
inline void Answer::_internal_set_id(::int64_t value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.id_ = value;
}

// required string questioner = 2;
inline bool Answer::has_questioner() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Answer::clear_questioner() {
  _impl_.questioner_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Answer::questioner() const {
  // @@protoc_insertion_point(field_get:yy.protobuf.Answer.questioner)
  return _internal_questioner();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Answer::set_questioner(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.questioner_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:yy.protobuf.Answer.questioner)
}
inline std::string* Answer::mutable_questioner() {
  std::string* _s = _internal_mutable_questioner();
  // @@protoc_insertion_point(field_mutable:yy.protobuf.Answer.questioner)
  return _s;
}
inline const std::string& Answer::_internal_questioner() const {
  return _impl_.questioner_.Get();
}
inline void Answer::_internal_set_questioner(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000001u;


  _impl_.questioner_.Set(value, GetArenaForAllocation());
}
inline std::string* Answer::_internal_mutable_questioner() {
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.questioner_.Mutable( GetArenaForAllocation());
}
inline std::string* Answer::release_questioner() {
  // @@protoc_insertion_point(field_release:yy.protobuf.Answer.questioner)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.questioner_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.questioner_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Answer::set_allocated_questioner(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.questioner_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.questioner_.IsDefault()) {
          _impl_.questioner_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:yy.protobuf.Answer.questioner)
}

// required string answerer = 3;
inline bool Answer::has_answerer() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void Answer::clear_answerer() {
  _impl_.answerer_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Answer::answerer() const {
  // @@protoc_insertion_point(field_get:yy.protobuf.Answer.answerer)
  return _internal_answerer();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Answer::set_answerer(Arg_&& arg,
                                                     Args_... args) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.answerer_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:yy.protobuf.Answer.answerer)
}
inline std::string* Answer::mutable_answerer() {
  std::string* _s = _internal_mutable_answerer();
  // @@protoc_insertion_point(field_mutable:yy.protobuf.Answer.answerer)
  return _s;
}
inline const std::string& Answer::_internal_answerer() const {
  return _impl_.answerer_.Get();
}
inline void Answer::_internal_set_answerer(const std::string& value) {
  _impl_._has_bits_[0] |= 0x00000002u;


  _impl_.answerer_.Set(value, GetArenaForAllocation());
}
inline std::string* Answer::_internal_mutable_answerer() {
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.answerer_.Mutable( GetArenaForAllocation());
}
inline std::string* Answer::release_answerer() {
  // @@protoc_insertion_point(field_release:yy.protobuf.Answer.answerer)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  auto* released = _impl_.answerer_.Release();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.answerer_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return released;
}
inline void Answer::set_allocated_answerer(std::string* value) {
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.answerer_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.answerer_.IsDefault()) {
          _impl_.answerer_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:yy.protobuf.Answer.answerer)
}

// repeated string solution = 4;
inline int Answer::_internal_solution_size() const {
  return _impl_.solution_.size();
}
inline int Answer::solution_size() const {
  return _internal_solution_size();
}
inline void Answer::clear_solution() {
  _internal_mutable_solution()->Clear();
}
inline std::string* Answer::add_solution() {
  std::string* _s = _internal_add_solution();
  // @@protoc_insertion_point(field_add_mutable:yy.protobuf.Answer.solution)
  return _s;
}
inline const std::string& Answer::solution(int index) const {
  // @@protoc_insertion_point(field_get:yy.protobuf.Answer.solution)
  return _internal_solution(index);
}
inline std::string* Answer::mutable_solution(int index) {
  // @@protoc_insertion_point(field_mutable:yy.protobuf.Answer.solution)
  return _internal_mutable_solution()->Mutable(index);
}
inline void Answer::set_solution(int index, const std::string& value) {
  _internal_mutable_solution()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:yy.protobuf.Answer.solution)
}
inline void Answer::set_solution(int index, std::string&& value) {
  _internal_mutable_solution()->Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:yy.protobuf.Answer.solution)
}
inline void Answer::set_solution(int index, const char* value) {
  ABSL_DCHECK(value != nullptr);
  _internal_mutable_solution()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:yy.protobuf.Answer.solution)
}
inline void Answer::set_solution(int index, const char* value,
                              std::size_t size) {
  _internal_mutable_solution()->Mutable(index)->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:yy.protobuf.Answer.solution)
}
inline void Answer::set_solution(int index, absl::string_view value) {
  _internal_mutable_solution()->Mutable(index)->assign(value.data(),
                                                     value.size());
  // @@protoc_insertion_point(field_set_string_piece:yy.protobuf.Answer.solution)
}
inline void Answer::add_solution(const std::string& value) {
  _internal_mutable_solution()->Add()->assign(value);
  // @@protoc_insertion_point(field_add:yy.protobuf.Answer.solution)
}
inline void Answer::add_solution(std::string&& value) {
  _internal_mutable_solution()->Add(std::move(value));
  // @@protoc_insertion_point(field_add:yy.protobuf.Answer.solution)
}
inline void Answer::add_solution(const char* value) {
  ABSL_DCHECK(value != nullptr);
  _internal_mutable_solution()->Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:yy.protobuf.Answer.solution)
}
inline void Answer::add_solution(const char* value, std::size_t size) {
  _internal_mutable_solution()->Add()->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:yy.protobuf.Answer.solution)
}
inline void Answer::add_solution(absl::string_view value) {
  _internal_mutable_solution()->Add()->assign(value.data(), value.size());
  // @@protoc_insertion_point(field_add_string_piece:yy.protobuf.Answer.solution)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Answer::solution() const {
  // @@protoc_insertion_point(field_list:yy.protobuf.Answer.solution)
  return _internal_solution();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* Answer::mutable_solution() {
  // @@protoc_insertion_point(field_mutable_list:yy.protobuf.Answer.solution)
  return _internal_mutable_solution();
}
inline const std::string& Answer::_internal_solution(int index) const {
  return _internal_solution().Get(index);
}
inline std::string* Answer::_internal_add_solution() {
  return _internal_mutable_solution()->Add();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
Answer::_internal_solution() const {
  return _impl_.solution_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
Answer::_internal_mutable_solution() {
  return &_impl_.solution_;
}

// -------------------------------------------------------------------

// Empty

// optional int32 id = 1;
inline bool Empty::has_id() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void Empty::clear_id() {
  _impl_.id_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::int32_t Empty::id() const {
  // @@protoc_insertion_point(field_get:yy.protobuf.Empty.id)
  return _internal_id();
}
inline void Empty::set_id(::int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:yy.protobuf.Empty.id)
}
inline ::int32_t Empty::_internal_id() const {
  return _impl_.id_;
}
inline void Empty::_internal_set_id(::int32_t value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.id_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
}  // namespace yy


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_query_2eproto_2epb_2eh
