// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gameprotocol.proto

#include "gameprotocol.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace yy {
namespace server {
namespace GameProtocol {
class PackageHeadDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<PackageHead> _instance;
} _PackageHead_default_instance_;
class XorBodyDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<XorBody> _instance;
} _XorBody_default_instance_;
class SecurityBodyDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SecurityBody> _instance;
} _SecurityBody_default_instance_;
class ResultBodyDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<ResultBody> _instance;
} _ResultBody_default_instance_;
}  // namespace GameProtocol
}  // namespace server
}  // namespace yy
static void InitDefaultsscc_info_PackageHead_gameprotocol_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::yy::server::GameProtocol::_PackageHead_default_instance_;
    new (ptr) ::yy::server::GameProtocol::PackageHead();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::yy::server::GameProtocol::PackageHead::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_PackageHead_gameprotocol_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_PackageHead_gameprotocol_2eproto}, {}};

static void InitDefaultsscc_info_ResultBody_gameprotocol_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::yy::server::GameProtocol::_ResultBody_default_instance_;
    new (ptr) ::yy::server::GameProtocol::ResultBody();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::yy::server::GameProtocol::ResultBody::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_ResultBody_gameprotocol_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_ResultBody_gameprotocol_2eproto}, {}};

static void InitDefaultsscc_info_SecurityBody_gameprotocol_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::yy::server::GameProtocol::_SecurityBody_default_instance_;
    new (ptr) ::yy::server::GameProtocol::SecurityBody();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::yy::server::GameProtocol::SecurityBody::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SecurityBody_gameprotocol_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_SecurityBody_gameprotocol_2eproto}, {}};

static void InitDefaultsscc_info_XorBody_gameprotocol_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::yy::server::GameProtocol::_XorBody_default_instance_;
    new (ptr) ::yy::server::GameProtocol::XorBody();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::yy::server::GameProtocol::XorBody::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_XorBody_gameprotocol_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_XorBody_gameprotocol_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_gameprotocol_2eproto[4];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_gameprotocol_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_gameprotocol_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_gameprotocol_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yy::server::GameProtocol::PackageHead, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::yy::server::GameProtocol::PackageHead, check_code_),
  PROTOBUF_FIELD_OFFSET(::yy::server::GameProtocol::PackageHead, length_),
  PROTOBUF_FIELD_OFFSET(::yy::server::GameProtocol::PackageHead, cmd_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yy::server::GameProtocol::XorBody, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::yy::server::GameProtocol::XorBody, xor_code_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yy::server::GameProtocol::SecurityBody, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::yy::server::GameProtocol::SecurityBody, app_id_),
  PROTOBUF_FIELD_OFFSET(::yy::server::GameProtocol::SecurityBody, app_version_),
  PROTOBUF_FIELD_OFFSET(::yy::server::GameProtocol::SecurityBody, app_md5_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::yy::server::GameProtocol::ResultBody, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::yy::server::GameProtocol::ResultBody, result_code_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::yy::server::GameProtocol::PackageHead)},
  { 8, -1, sizeof(::yy::server::GameProtocol::XorBody)},
  { 14, -1, sizeof(::yy::server::GameProtocol::SecurityBody)},
  { 22, -1, sizeof(::yy::server::GameProtocol::ResultBody)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::yy::server::GameProtocol::_PackageHead_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::yy::server::GameProtocol::_XorBody_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::yy::server::GameProtocol::_SecurityBody_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::yy::server::GameProtocol::_ResultBody_default_instance_),
};

const char descriptor_table_protodef_gameprotocol_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\022gameprotocol.proto\022\026yy.server.GameProt"
  "ocol\"h\n\013PackageHead\022\022\n\ncheck_code\030\001 \001(\014\022"
  "\016\n\006length\030\002 \001(\r\0225\n\003cmd\030\003 \001(\0162(.yy.server"
  ".GameProtocol.E_PackageCommand\"\033\n\007XorBod"
  "y\022\020\n\010xor_code\030\001 \001(\r\"D\n\014SecurityBody\022\016\n\006a"
  "pp_id\030\001 \001(\r\022\023\n\013app_version\030\002 \001(\r\022\017\n\007app_"
  "md5\030\003 \001(\t\"E\n\nResultBody\0227\n\013result_code\030\001"
  " \001(\0162\".yy.server.GameProtocol.ResultCode"
  "*\231\001\n\020E_PackageCommand\022\t\n\005eTest\020\000\022\013\n\006eLog"
  "in\020\350\007\022\n\n\005eMove\020\320\017\022\023\n\016eGetPlayerData\020\270\027\022\013"
  "\n\006eLeave\020\240\037\022\024\n\017eJumpAndGravity\020\210\'\022\014\n\006eHe"
  "art\020\350\373\003\022\n\n\004eXor\020\373\377\003\022\017\n\teSecurity\020\374\377\003*A\n\n"
  "ResultCode\022\014\n\010eSuccess\020\000\022\025\n\021eAppVersionF"
  "ailed\020\001\022\016\n\neMd5Failed\020\002b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_gameprotocol_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_gameprotocol_2eproto_sccs[4] = {
  &scc_info_PackageHead_gameprotocol_2eproto.base,
  &scc_info_ResultBody_gameprotocol_2eproto.base,
  &scc_info_SecurityBody_gameprotocol_2eproto.base,
  &scc_info_XorBody_gameprotocol_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_gameprotocol_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_gameprotocol_2eproto = {
  false, false, descriptor_table_protodef_gameprotocol_2eproto, "gameprotocol.proto", 551,
  &descriptor_table_gameprotocol_2eproto_once, descriptor_table_gameprotocol_2eproto_sccs, descriptor_table_gameprotocol_2eproto_deps, 4, 0,
  schemas, file_default_instances, TableStruct_gameprotocol_2eproto::offsets,
  file_level_metadata_gameprotocol_2eproto, 4, file_level_enum_descriptors_gameprotocol_2eproto, file_level_service_descriptors_gameprotocol_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_gameprotocol_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_gameprotocol_2eproto)), true);
namespace yy {
namespace server {
namespace GameProtocol {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* E_PackageCommand_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_gameprotocol_2eproto);
  return file_level_enum_descriptors_gameprotocol_2eproto[0];
}
bool E_PackageCommand_IsValid(int value) {
  switch (value) {
    case 0:
    case 1000:
    case 2000:
    case 3000:
    case 4000:
    case 5000:
    case 65000:
    case 65531:
    case 65532:
      return true;
    default:
      return false;
  }
}

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ResultCode_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_gameprotocol_2eproto);
  return file_level_enum_descriptors_gameprotocol_2eproto[1];
}
bool ResultCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void PackageHead::InitAsDefaultInstance() {
}
class PackageHead::_Internal {
 public:
};

PackageHead::PackageHead(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:yy.server.GameProtocol.PackageHead)
}
PackageHead::PackageHead(const PackageHead& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  check_code_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_check_code().empty()) {
    check_code_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_check_code(),
      GetArena());
  }
  ::memcpy(&length_, &from.length_,
    static_cast<size_t>(reinterpret_cast<char*>(&cmd_) -
    reinterpret_cast<char*>(&length_)) + sizeof(cmd_));
  // @@protoc_insertion_point(copy_constructor:yy.server.GameProtocol.PackageHead)
}

void PackageHead::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_PackageHead_gameprotocol_2eproto.base);
  check_code_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&length_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&cmd_) -
      reinterpret_cast<char*>(&length_)) + sizeof(cmd_));
}

PackageHead::~PackageHead() {
  // @@protoc_insertion_point(destructor:yy.server.GameProtocol.PackageHead)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void PackageHead::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  check_code_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void PackageHead::ArenaDtor(void* object) {
  PackageHead* _this = reinterpret_cast< PackageHead* >(object);
  (void)_this;
}
void PackageHead::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void PackageHead::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const PackageHead& PackageHead::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_PackageHead_gameprotocol_2eproto.base);
  return *internal_default_instance();
}


void PackageHead::Clear() {
// @@protoc_insertion_point(message_clear_start:yy.server.GameProtocol.PackageHead)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  check_code_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&length_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&cmd_) -
      reinterpret_cast<char*>(&length_)) + sizeof(cmd_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* PackageHead::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // bytes check_code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_check_code();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 length = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          length_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .yy.server.GameProtocol.E_PackageCommand cmd = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_cmd(static_cast<::yy::server::GameProtocol::E_PackageCommand>(val));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* PackageHead::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yy.server.GameProtocol.PackageHead)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes check_code = 1;
  if (this->check_code().size() > 0) {
    target = stream->WriteBytesMaybeAliased(
        1, this->_internal_check_code(), target);
  }

  // uint32 length = 2;
  if (this->length() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_length(), target);
  }

  // .yy.server.GameProtocol.E_PackageCommand cmd = 3;
  if (this->cmd() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      3, this->_internal_cmd(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yy.server.GameProtocol.PackageHead)
  return target;
}

size_t PackageHead::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yy.server.GameProtocol.PackageHead)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes check_code = 1;
  if (this->check_code().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_check_code());
  }

  // uint32 length = 2;
  if (this->length() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_length());
  }

  // .yy.server.GameProtocol.E_PackageCommand cmd = 3;
  if (this->cmd() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_cmd());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PackageHead::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:yy.server.GameProtocol.PackageHead)
  GOOGLE_DCHECK_NE(&from, this);
  const PackageHead* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<PackageHead>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:yy.server.GameProtocol.PackageHead)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:yy.server.GameProtocol.PackageHead)
    MergeFrom(*source);
  }
}

void PackageHead::MergeFrom(const PackageHead& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yy.server.GameProtocol.PackageHead)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.check_code().size() > 0) {
    _internal_set_check_code(from._internal_check_code());
  }
  if (from.length() != 0) {
    _internal_set_length(from._internal_length());
  }
  if (from.cmd() != 0) {
    _internal_set_cmd(from._internal_cmd());
  }
}

void PackageHead::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:yy.server.GameProtocol.PackageHead)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PackageHead::CopyFrom(const PackageHead& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yy.server.GameProtocol.PackageHead)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PackageHead::IsInitialized() const {
  return true;
}

void PackageHead::InternalSwap(PackageHead* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  check_code_.Swap(&other->check_code_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PackageHead, cmd_)
      + sizeof(PackageHead::cmd_)
      - PROTOBUF_FIELD_OFFSET(PackageHead, length_)>(
          reinterpret_cast<char*>(&length_),
          reinterpret_cast<char*>(&other->length_));
}

::PROTOBUF_NAMESPACE_ID::Metadata PackageHead::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void XorBody::InitAsDefaultInstance() {
}
class XorBody::_Internal {
 public:
};

XorBody::XorBody(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:yy.server.GameProtocol.XorBody)
}
XorBody::XorBody(const XorBody& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  xor_code_ = from.xor_code_;
  // @@protoc_insertion_point(copy_constructor:yy.server.GameProtocol.XorBody)
}

void XorBody::SharedCtor() {
  xor_code_ = 0u;
}

XorBody::~XorBody() {
  // @@protoc_insertion_point(destructor:yy.server.GameProtocol.XorBody)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void XorBody::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void XorBody::ArenaDtor(void* object) {
  XorBody* _this = reinterpret_cast< XorBody* >(object);
  (void)_this;
}
void XorBody::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void XorBody::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const XorBody& XorBody::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_XorBody_gameprotocol_2eproto.base);
  return *internal_default_instance();
}


void XorBody::Clear() {
// @@protoc_insertion_point(message_clear_start:yy.server.GameProtocol.XorBody)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  xor_code_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* XorBody::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 xor_code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          xor_code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* XorBody::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yy.server.GameProtocol.XorBody)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 xor_code = 1;
  if (this->xor_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_xor_code(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yy.server.GameProtocol.XorBody)
  return target;
}

size_t XorBody::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yy.server.GameProtocol.XorBody)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 xor_code = 1;
  if (this->xor_code() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_xor_code());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void XorBody::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:yy.server.GameProtocol.XorBody)
  GOOGLE_DCHECK_NE(&from, this);
  const XorBody* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<XorBody>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:yy.server.GameProtocol.XorBody)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:yy.server.GameProtocol.XorBody)
    MergeFrom(*source);
  }
}

void XorBody::MergeFrom(const XorBody& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yy.server.GameProtocol.XorBody)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.xor_code() != 0) {
    _internal_set_xor_code(from._internal_xor_code());
  }
}

void XorBody::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:yy.server.GameProtocol.XorBody)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void XorBody::CopyFrom(const XorBody& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yy.server.GameProtocol.XorBody)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool XorBody::IsInitialized() const {
  return true;
}

void XorBody::InternalSwap(XorBody* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(xor_code_, other->xor_code_);
}

::PROTOBUF_NAMESPACE_ID::Metadata XorBody::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void SecurityBody::InitAsDefaultInstance() {
}
class SecurityBody::_Internal {
 public:
};

SecurityBody::SecurityBody(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:yy.server.GameProtocol.SecurityBody)
}
SecurityBody::SecurityBody(const SecurityBody& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  app_md5_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_app_md5().empty()) {
    app_md5_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), from._internal_app_md5(),
      GetArena());
  }
  ::memcpy(&app_id_, &from.app_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&app_version_) -
    reinterpret_cast<char*>(&app_id_)) + sizeof(app_version_));
  // @@protoc_insertion_point(copy_constructor:yy.server.GameProtocol.SecurityBody)
}

void SecurityBody::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_SecurityBody_gameprotocol_2eproto.base);
  app_md5_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(&app_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&app_version_) -
      reinterpret_cast<char*>(&app_id_)) + sizeof(app_version_));
}

SecurityBody::~SecurityBody() {
  // @@protoc_insertion_point(destructor:yy.server.GameProtocol.SecurityBody)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SecurityBody::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  app_md5_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void SecurityBody::ArenaDtor(void* object) {
  SecurityBody* _this = reinterpret_cast< SecurityBody* >(object);
  (void)_this;
}
void SecurityBody::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SecurityBody::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SecurityBody& SecurityBody::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SecurityBody_gameprotocol_2eproto.base);
  return *internal_default_instance();
}


void SecurityBody::Clear() {
// @@protoc_insertion_point(message_clear_start:yy.server.GameProtocol.SecurityBody)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  app_md5_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::memset(&app_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&app_version_) -
      reinterpret_cast<char*>(&app_id_)) + sizeof(app_version_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SecurityBody::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 app_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          app_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 app_version = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          app_version_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string app_md5 = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          auto str = _internal_mutable_app_md5();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "yy.server.GameProtocol.SecurityBody.app_md5"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SecurityBody::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yy.server.GameProtocol.SecurityBody)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 app_id = 1;
  if (this->app_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_app_id(), target);
  }

  // uint32 app_version = 2;
  if (this->app_version() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_app_version(), target);
  }

  // string app_md5 = 3;
  if (this->app_md5().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_app_md5().data(), static_cast<int>(this->_internal_app_md5().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "yy.server.GameProtocol.SecurityBody.app_md5");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_app_md5(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yy.server.GameProtocol.SecurityBody)
  return target;
}

size_t SecurityBody::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yy.server.GameProtocol.SecurityBody)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string app_md5 = 3;
  if (this->app_md5().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_app_md5());
  }

  // uint32 app_id = 1;
  if (this->app_id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_app_id());
  }

  // uint32 app_version = 2;
  if (this->app_version() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_app_version());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SecurityBody::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:yy.server.GameProtocol.SecurityBody)
  GOOGLE_DCHECK_NE(&from, this);
  const SecurityBody* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SecurityBody>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:yy.server.GameProtocol.SecurityBody)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:yy.server.GameProtocol.SecurityBody)
    MergeFrom(*source);
  }
}

void SecurityBody::MergeFrom(const SecurityBody& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yy.server.GameProtocol.SecurityBody)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.app_md5().size() > 0) {
    _internal_set_app_md5(from._internal_app_md5());
  }
  if (from.app_id() != 0) {
    _internal_set_app_id(from._internal_app_id());
  }
  if (from.app_version() != 0) {
    _internal_set_app_version(from._internal_app_version());
  }
}

void SecurityBody::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:yy.server.GameProtocol.SecurityBody)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SecurityBody::CopyFrom(const SecurityBody& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yy.server.GameProtocol.SecurityBody)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SecurityBody::IsInitialized() const {
  return true;
}

void SecurityBody::InternalSwap(SecurityBody* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  app_md5_.Swap(&other->app_md5_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SecurityBody, app_version_)
      + sizeof(SecurityBody::app_version_)
      - PROTOBUF_FIELD_OFFSET(SecurityBody, app_id_)>(
          reinterpret_cast<char*>(&app_id_),
          reinterpret_cast<char*>(&other->app_id_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SecurityBody::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

void ResultBody::InitAsDefaultInstance() {
}
class ResultBody::_Internal {
 public:
};

ResultBody::ResultBody(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:yy.server.GameProtocol.ResultBody)
}
ResultBody::ResultBody(const ResultBody& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  result_code_ = from.result_code_;
  // @@protoc_insertion_point(copy_constructor:yy.server.GameProtocol.ResultBody)
}

void ResultBody::SharedCtor() {
  result_code_ = 0;
}

ResultBody::~ResultBody() {
  // @@protoc_insertion_point(destructor:yy.server.GameProtocol.ResultBody)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ResultBody::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void ResultBody::ArenaDtor(void* object) {
  ResultBody* _this = reinterpret_cast< ResultBody* >(object);
  (void)_this;
}
void ResultBody::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ResultBody::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ResultBody& ResultBody::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_ResultBody_gameprotocol_2eproto.base);
  return *internal_default_instance();
}


void ResultBody::Clear() {
// @@protoc_insertion_point(message_clear_start:yy.server.GameProtocol.ResultBody)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  result_code_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ResultBody::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .yy.server.GameProtocol.ResultCode result_code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_result_code(static_cast<::yy::server::GameProtocol::ResultCode>(val));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ResultBody::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:yy.server.GameProtocol.ResultBody)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .yy.server.GameProtocol.ResultCode result_code = 1;
  if (this->result_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_result_code(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:yy.server.GameProtocol.ResultBody)
  return target;
}

size_t ResultBody::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:yy.server.GameProtocol.ResultBody)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .yy.server.GameProtocol.ResultCode result_code = 1;
  if (this->result_code() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_result_code());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ResultBody::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:yy.server.GameProtocol.ResultBody)
  GOOGLE_DCHECK_NE(&from, this);
  const ResultBody* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ResultBody>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:yy.server.GameProtocol.ResultBody)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:yy.server.GameProtocol.ResultBody)
    MergeFrom(*source);
  }
}

void ResultBody::MergeFrom(const ResultBody& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:yy.server.GameProtocol.ResultBody)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.result_code() != 0) {
    _internal_set_result_code(from._internal_result_code());
  }
}

void ResultBody::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:yy.server.GameProtocol.ResultBody)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ResultBody::CopyFrom(const ResultBody& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:yy.server.GameProtocol.ResultBody)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResultBody::IsInitialized() const {
  return true;
}

void ResultBody::InternalSwap(ResultBody* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(result_code_, other->result_code_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ResultBody::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace GameProtocol
}  // namespace server
}  // namespace yy
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::yy::server::GameProtocol::PackageHead* Arena::CreateMaybeMessage< ::yy::server::GameProtocol::PackageHead >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yy::server::GameProtocol::PackageHead >(arena);
}
template<> PROTOBUF_NOINLINE ::yy::server::GameProtocol::XorBody* Arena::CreateMaybeMessage< ::yy::server::GameProtocol::XorBody >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yy::server::GameProtocol::XorBody >(arena);
}
template<> PROTOBUF_NOINLINE ::yy::server::GameProtocol::SecurityBody* Arena::CreateMaybeMessage< ::yy::server::GameProtocol::SecurityBody >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yy::server::GameProtocol::SecurityBody >(arena);
}
template<> PROTOBUF_NOINLINE ::yy::server::GameProtocol::ResultBody* Arena::CreateMaybeMessage< ::yy::server::GameProtocol::ResultBody >(Arena* arena) {
  return Arena::CreateMessageInternal< ::yy::server::GameProtocol::ResultBody >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
